// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbx/fss.proto

package pbx

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd443f5ff6bae6bb, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// ----------------------------------------
// Provider Model
// ----------------------------------------
type Provider struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd443f5ff6bae6bb, []int{1}
}

func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Provider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Container struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd443f5ff6bae6bb, []int{2}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type GetContainersRequest struct {
	Filter               string         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GetContainersRequest) Reset()         { *m = GetContainersRequest{} }
func (m *GetContainersRequest) String() string { return proto.CompactTextString(m) }
func (*GetContainersRequest) ProtoMessage()    {}
func (*GetContainersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd443f5ff6bae6bb, []int{3}
}

func (m *GetContainersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContainersRequest.Unmarshal(m, b)
}
func (m *GetContainersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContainersRequest.Marshal(b, m, deterministic)
}
func (m *GetContainersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContainersRequest.Merge(m, src)
}
func (m *GetContainersRequest) XXX_Size() int {
	return xxx_messageInfo_GetContainersRequest.Size(m)
}
func (m *GetContainersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContainersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetContainersRequest proto.InternalMessageInfo

func (m *GetContainersRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *GetContainersRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type GetContainersResponse struct {
	Containers           []*Container `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *GetContainersResponse) Reset()         { *m = GetContainersResponse{} }
func (m *GetContainersResponse) String() string { return proto.CompactTextString(m) }
func (*GetContainersResponse) ProtoMessage()    {}
func (*GetContainersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd443f5ff6bae6bb, []int{4}
}

func (m *GetContainersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetContainersResponse.Unmarshal(m, b)
}
func (m *GetContainersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetContainersResponse.Marshal(b, m, deterministic)
}
func (m *GetContainersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetContainersResponse.Merge(m, src)
}
func (m *GetContainersResponse) XXX_Size() int {
	return xxx_messageInfo_GetContainersResponse.Size(m)
}
func (m *GetContainersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetContainersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetContainersResponse proto.InternalMessageInfo

func (m *GetContainersResponse) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "pbx.Empty")
	proto.RegisterType((*Provider)(nil), "pbx.Provider")
	proto.RegisterType((*Container)(nil), "pbx.Container")
	proto.RegisterType((*GetContainersRequest)(nil), "pbx.GetContainersRequest")
	proto.RegisterType((*GetContainersResponse)(nil), "pbx.GetContainersResponse")
}

func init() { proto.RegisterFile("pbx/fss.proto", fileDescriptor_bd443f5ff6bae6bb) }

var fileDescriptor_bd443f5ff6bae6bb = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x4d, 0x4b, 0xc3, 0x40,
	0x10, 0x86, 0x49, 0xaa, 0xd1, 0x4e, 0x69, 0x90, 0x41, 0x25, 0xe6, 0x62, 0xc9, 0xa9, 0x78, 0x58,
	0x21, 0xfe, 0x04, 0x31, 0xf5, 0x28, 0xf1, 0x22, 0xde, 0xf2, 0x31, 0xc5, 0x85, 0x66, 0x77, 0xdd,
	0x59, 0x4b, 0xfc, 0xf7, 0xe2, 0x36, 0x84, 0x2a, 0xb9, 0xed, 0x3e, 0xf3, 0xbc, 0xef, 0x7e, 0xc0,
	0xd2, 0xd4, 0xfd, 0xfd, 0x96, 0x59, 0x18, 0xab, 0x9d, 0xc6, 0x99, 0xa9, 0xfb, 0xf4, 0xe2, 0x97,
	0x35, 0xba, 0xeb, 0xb4, 0x3a, 0xe0, 0xec, 0x0c, 0x4e, 0x9f, 0x3a, 0xe3, 0xbe, 0x33, 0x01, 0xe7,
	0x2f, 0x56, 0xef, 0x65, 0x4b, 0x16, 0x63, 0x08, 0x65, 0x9b, 0x04, 0xab, 0x60, 0x3d, 0x2f, 0x43,
	0xd9, 0x22, 0xc2, 0x89, 0xaa, 0x3a, 0x4a, 0x42, 0x4f, 0xfc, 0x3a, 0xbb, 0x85, 0xf9, 0xa3, 0x56,
	0xae, 0x92, 0x8a, 0xec, 0x28, 0x04, 0x47, 0xc2, 0x3b, 0x5c, 0x6e, 0xc8, 0x8d, 0x0e, 0x97, 0xf4,
	0xf9, 0x45, 0xec, 0xf0, 0x1a, 0xa2, 0xad, 0xdc, 0x39, 0xb2, 0x83, 0x3d, 0xec, 0xf0, 0x0e, 0xa2,
	0x0f, 0xaa, 0x5a, 0xb2, 0xfe, 0x98, 0x45, 0x8e, 0xc2, 0xd4, 0xbd, 0x18, 0x52, 0xcf, 0x7e, 0x52,
	0x0e, 0x46, 0xb6, 0x81, 0xab, 0x7f, 0xdd, 0x6c, 0xb4, 0x62, 0x42, 0x01, 0xd0, 0x8c, 0x34, 0x09,
	0x56, 0xb3, 0xf5, 0x22, 0x8f, 0x7d, 0xd1, 0x28, 0x97, 0x47, 0x46, 0xfe, 0x06, 0x71, 0xb1, 0xa3,
	0xbe, 0x60, 0x7e, 0x25, 0xbb, 0x97, 0x0d, 0x61, 0x01, 0xcb, 0x3f, 0xd5, 0x78, 0xe3, 0xe3, 0x53,
	0x4f, 0x49, 0xd3, 0xa9, 0xd1, 0xe1, 0x26, 0x75, 0xe4, 0xff, 0xf7, 0xe1, 0x27, 0x00, 0x00, 0xff,
	0xff, 0x14, 0x1c, 0x23, 0x9e, 0x87, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FlexFssServiceClient is the client API for FlexFssService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlexFssServiceClient interface {
	GetContainers(ctx context.Context, in *GetContainersRequest, opts ...grpc.CallOption) (*GetContainersResponse, error)
}

type flexFssServiceClient struct {
	cc *grpc.ClientConn
}

func NewFlexFssServiceClient(cc *grpc.ClientConn) FlexFssServiceClient {
	return &flexFssServiceClient{cc}
}

func (c *flexFssServiceClient) GetContainers(ctx context.Context, in *GetContainersRequest, opts ...grpc.CallOption) (*GetContainersResponse, error) {
	out := new(GetContainersResponse)
	err := c.cc.Invoke(ctx, "/pbx.FlexFssService/GetContainers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlexFssServiceServer is the server API for FlexFssService service.
type FlexFssServiceServer interface {
	GetContainers(context.Context, *GetContainersRequest) (*GetContainersResponse, error)
}

// UnimplementedFlexFssServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFlexFssServiceServer struct {
}

func (*UnimplementedFlexFssServiceServer) GetContainers(ctx context.Context, req *GetContainersRequest) (*GetContainersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetContainers not implemented")
}

func RegisterFlexFssServiceServer(s *grpc.Server, srv FlexFssServiceServer) {
	s.RegisterService(&_FlexFssService_serviceDesc, srv)
}

func _FlexFssService_GetContainers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetContainersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexFssServiceServer).GetContainers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.FlexFssService/GetContainers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexFssServiceServer).GetContainers(ctx, req.(*GetContainersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlexFssService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbx.FlexFssService",
	HandlerType: (*FlexFssServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetContainers",
			Handler:    _FlexFssService_GetContainers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbx/fss.proto",
}
