// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbx/fss.proto

package pbx

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd443f5ff6bae6bb, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// ----------------------------------------
// Provider Model
// ----------------------------------------
type Provider struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Provider) Reset()         { *m = Provider{} }
func (m *Provider) String() string { return proto.CompactTextString(m) }
func (*Provider) ProtoMessage()    {}
func (*Provider) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd443f5ff6bae6bb, []int{1}
}

func (m *Provider) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Provider.Unmarshal(m, b)
}
func (m *Provider) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Provider.Marshal(b, m, deterministic)
}
func (m *Provider) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Provider.Merge(m, src)
}
func (m *Provider) XXX_Size() int {
	return xxx_messageInfo_Provider.Size(m)
}
func (m *Provider) XXX_DiscardUnknown() {
	xxx_messageInfo_Provider.DiscardUnknown(m)
}

var xxx_messageInfo_Provider proto.InternalMessageInfo

func (m *Provider) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Provider) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type Container struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Container) Reset()         { *m = Container{} }
func (m *Container) String() string { return proto.CompactTextString(m) }
func (*Container) ProtoMessage()    {}
func (*Container) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd443f5ff6bae6bb, []int{2}
}

func (m *Container) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Container.Unmarshal(m, b)
}
func (m *Container) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Container.Marshal(b, m, deterministic)
}
func (m *Container) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Container.Merge(m, src)
}
func (m *Container) XXX_Size() int {
	return xxx_messageInfo_Container.Size(m)
}
func (m *Container) XXX_DiscardUnknown() {
	xxx_messageInfo_Container.DiscardUnknown(m)
}

var xxx_messageInfo_Container proto.InternalMessageInfo

func (m *Container) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type ContainerFindRequest struct {
	Filter               string         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ContainerFindRequest) Reset()         { *m = ContainerFindRequest{} }
func (m *ContainerFindRequest) String() string { return proto.CompactTextString(m) }
func (*ContainerFindRequest) ProtoMessage()    {}
func (*ContainerFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd443f5ff6bae6bb, []int{3}
}

func (m *ContainerFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerFindRequest.Unmarshal(m, b)
}
func (m *ContainerFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerFindRequest.Marshal(b, m, deterministic)
}
func (m *ContainerFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerFindRequest.Merge(m, src)
}
func (m *ContainerFindRequest) XXX_Size() int {
	return xxx_messageInfo_ContainerFindRequest.Size(m)
}
func (m *ContainerFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerFindRequest proto.InternalMessageInfo

func (m *ContainerFindRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *ContainerFindRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type ContainerFindResponse struct {
	Containers           []*Container `protobuf:"bytes,1,rep,name=containers,proto3" json:"containers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *ContainerFindResponse) Reset()         { *m = ContainerFindResponse{} }
func (m *ContainerFindResponse) String() string { return proto.CompactTextString(m) }
func (*ContainerFindResponse) ProtoMessage()    {}
func (*ContainerFindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_bd443f5ff6bae6bb, []int{4}
}

func (m *ContainerFindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ContainerFindResponse.Unmarshal(m, b)
}
func (m *ContainerFindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ContainerFindResponse.Marshal(b, m, deterministic)
}
func (m *ContainerFindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ContainerFindResponse.Merge(m, src)
}
func (m *ContainerFindResponse) XXX_Size() int {
	return xxx_messageInfo_ContainerFindResponse.Size(m)
}
func (m *ContainerFindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ContainerFindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ContainerFindResponse proto.InternalMessageInfo

func (m *ContainerFindResponse) GetContainers() []*Container {
	if m != nil {
		return m.Containers
	}
	return nil
}

func init() {
	proto.RegisterType((*Empty)(nil), "pbx.Empty")
	proto.RegisterType((*Provider)(nil), "pbx.Provider")
	proto.RegisterType((*Container)(nil), "pbx.Container")
	proto.RegisterType((*ContainerFindRequest)(nil), "pbx.ContainerFindRequest")
	proto.RegisterType((*ContainerFindResponse)(nil), "pbx.ContainerFindResponse")
}

func init() { proto.RegisterFile("pbx/fss.proto", fileDescriptor_bd443f5ff6bae6bb) }

var fileDescriptor_bd443f5ff6bae6bb = []byte{
	// 251 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x90, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0x69, 0x57, 0xab, 0x3b, 0xcb, 0x16, 0x19, 0x54, 0x6a, 0x2f, 0x2e, 0x3d, 0x2d, 0x1e,
	0x22, 0xd4, 0x9f, 0x20, 0x56, 0x8f, 0x52, 0x2f, 0xe2, 0xad, 0x6d, 0x66, 0x31, 0xb0, 0x4d, 0x62,
	0x12, 0x97, 0xfa, 0xef, 0xc5, 0x6c, 0x2c, 0x5d, 0xf1, 0x96, 0xbc, 0xf7, 0xbd, 0x97, 0xcc, 0xc0,
	0x52, 0xb7, 0xc3, 0xed, 0xc6, 0x5a, 0xa6, 0x8d, 0x72, 0x0a, 0x67, 0xba, 0x1d, 0xf2, 0xb3, 0x1f,
	0xad, 0x53, 0x7d, 0xaf, 0xe4, 0x5e, 0x2e, 0x4e, 0xe0, 0xf8, 0xa1, 0xd7, 0xee, 0xab, 0x60, 0x70,
	0xfa, 0x6c, 0xd4, 0x4e, 0x70, 0x32, 0x98, 0x42, 0x2c, 0x78, 0x16, 0xad, 0xa2, 0xf5, 0xbc, 0x8e,
	0x05, 0x47, 0x84, 0x23, 0xd9, 0xf4, 0x94, 0xc5, 0x5e, 0xf1, 0xe7, 0xe2, 0x1a, 0xe6, 0xf7, 0x4a,
	0xba, 0x46, 0x48, 0x32, 0x23, 0x10, 0x4d, 0x80, 0x37, 0x38, 0x1f, 0x81, 0x4a, 0x48, 0x5e, 0xd3,
	0xc7, 0x27, 0x59, 0x87, 0x97, 0x90, 0x6c, 0xc4, 0xd6, 0x91, 0x09, 0x74, 0xb8, 0xe1, 0x0d, 0x24,
	0xef, 0xd4, 0x70, 0x32, 0xfe, 0x99, 0x45, 0x89, 0x4c, 0xb7, 0x03, 0x0b, 0xa9, 0x27, 0xef, 0xd4,
	0x81, 0x28, 0x1e, 0xe1, 0xe2, 0x4f, 0xb7, 0xd5, 0x4a, 0x5a, 0x42, 0x06, 0xd0, 0xfd, 0x1a, 0x36,
	0x8b, 0x56, 0xb3, 0xf5, 0xa2, 0x4c, 0x7d, 0xd1, 0xc8, 0xd7, 0x13, 0xa2, 0x7c, 0x85, 0xb4, 0xda,
	0xd2, 0x50, 0x59, 0xfb, 0x42, 0x66, 0x27, 0x3a, 0xc2, 0x0a, 0x96, 0x07, 0xd5, 0x78, 0x75, 0x18,
	0x9f, 0x8c, 0x92, 0xe7, 0xff, 0x59, 0xfb, 0x9f, 0xb4, 0x89, 0xdf, 0xef, 0xdd, 0x77, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x73, 0x87, 0x60, 0xe1, 0x87, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// FlexFssServiceClient is the client API for FlexFssService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type FlexFssServiceClient interface {
	ContainerFind(ctx context.Context, in *ContainerFindRequest, opts ...grpc.CallOption) (*ContainerFindResponse, error)
}

type flexFssServiceClient struct {
	cc *grpc.ClientConn
}

func NewFlexFssServiceClient(cc *grpc.ClientConn) FlexFssServiceClient {
	return &flexFssServiceClient{cc}
}

func (c *flexFssServiceClient) ContainerFind(ctx context.Context, in *ContainerFindRequest, opts ...grpc.CallOption) (*ContainerFindResponse, error) {
	out := new(ContainerFindResponse)
	err := c.cc.Invoke(ctx, "/pbx.FlexFssService/ContainerFind", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FlexFssServiceServer is the server API for FlexFssService service.
type FlexFssServiceServer interface {
	ContainerFind(context.Context, *ContainerFindRequest) (*ContainerFindResponse, error)
}

// UnimplementedFlexFssServiceServer can be embedded to have forward compatible implementations.
type UnimplementedFlexFssServiceServer struct {
}

func (*UnimplementedFlexFssServiceServer) ContainerFind(ctx context.Context, req *ContainerFindRequest) (*ContainerFindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ContainerFind not implemented")
}

func RegisterFlexFssServiceServer(s *grpc.Server, srv FlexFssServiceServer) {
	s.RegisterService(&_FlexFssService_serviceDesc, srv)
}

func _FlexFssService_ContainerFind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ContainerFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FlexFssServiceServer).ContainerFind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.FlexFssService/ContainerFind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FlexFssServiceServer).ContainerFind(ctx, req.(*ContainerFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _FlexFssService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbx.FlexFssService",
	HandlerType: (*FlexFssServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ContainerFind",
			Handler:    _FlexFssService_ContainerFind_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbx/fss.proto",
}
