// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbx/iam.proto

package pbx

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN     HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING     HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING HealthCheckResponse_ServingStatus = 2
)

var HealthCheckResponse_ServingStatus_name = map[int32]string{
	0: "UNKNOWN",
	1: "SERVING",
	2: "NOT_SERVING",
}

var HealthCheckResponse_ServingStatus_value = map[string]int32{
	"UNKNOWN":     0,
	"SERVING":     1,
	"NOT_SERVING": 2,
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return proto.EnumName(HealthCheckResponse_ServingStatus_name, int32(x))
}

func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{2, 0}
}

type Empty struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Empty) Reset()         { *m = Empty{} }
func (m *Empty) String() string { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()    {}
func (*Empty) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{0}
}

func (m *Empty) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Empty.Unmarshal(m, b)
}
func (m *Empty) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Empty.Marshal(b, m, deterministic)
}
func (m *Empty) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Empty.Merge(m, src)
}
func (m *Empty) XXX_Size() int {
	return xxx_messageInfo_Empty.Size(m)
}
func (m *Empty) XXX_DiscardUnknown() {
	xxx_messageInfo_Empty.DiscardUnknown(m)
}

var xxx_messageInfo_Empty proto.InternalMessageInfo

// ----------------------------------------
// HealthCheck
// ----------------------------------------
type HealthCheckRequest struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HealthCheckRequest) Reset()         { *m = HealthCheckRequest{} }
func (m *HealthCheckRequest) String() string { return proto.CompactTextString(m) }
func (*HealthCheckRequest) ProtoMessage()    {}
func (*HealthCheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{1}
}

func (m *HealthCheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckRequest.Unmarshal(m, b)
}
func (m *HealthCheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckRequest.Marshal(b, m, deterministic)
}
func (m *HealthCheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckRequest.Merge(m, src)
}
func (m *HealthCheckRequest) XXX_Size() int {
	return xxx_messageInfo_HealthCheckRequest.Size(m)
}
func (m *HealthCheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckRequest proto.InternalMessageInfo

func (m *HealthCheckRequest) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

type HealthCheckResponse struct {
	Status               HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=pbx.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *HealthCheckResponse) Reset()         { *m = HealthCheckResponse{} }
func (m *HealthCheckResponse) String() string { return proto.CompactTextString(m) }
func (*HealthCheckResponse) ProtoMessage()    {}
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{2}
}

func (m *HealthCheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HealthCheckResponse.Unmarshal(m, b)
}
func (m *HealthCheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HealthCheckResponse.Marshal(b, m, deterministic)
}
func (m *HealthCheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HealthCheckResponse.Merge(m, src)
}
func (m *HealthCheckResponse) XXX_Size() int {
	return xxx_messageInfo_HealthCheckResponse.Size(m)
}
func (m *HealthCheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_HealthCheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_HealthCheckResponse proto.InternalMessageInfo

func (m *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if m != nil {
		return m.Status
	}
	return HealthCheckResponse_UNKNOWN
}

// ----------------------------------------
// AdminUser Model
// ----------------------------------------
type AdminUser struct {
	Id                   string               `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Username             string               `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Password             string               `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Fullname             string               `protobuf:"bytes,4,opt,name=fullname,proto3" json:"fullname,omitempty"`
	Email                string               `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	AccountAccess        bool                 `protobuf:"varint,6,opt,name=account_access,json=accountAccess,proto3" json:"account_access,omitempty"`
	LoginCounter         int32                `protobuf:"varint,7,opt,name=login_counter,json=loginCounter,proto3" json:"login_counter,omitempty"`
	LastLogin            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=last_login,json=lastLogin,proto3" json:"last_login,omitempty"`
	AccountExpiry        *timestamp.Timestamp `protobuf:"bytes,9,opt,name=account_expiry,json=accountExpiry,proto3" json:"account_expiry,omitempty"`
	Photo                string               `protobuf:"bytes,10,opt,name=photo,proto3" json:"photo,omitempty"`
	PwdExpiry            bool                 `protobuf:"varint,11,opt,name=pwd_expiry,json=pwdExpiry,proto3" json:"pwd_expiry,omitempty"`
	PwdExpiryTime        *timestamp.Timestamp `protobuf:"bytes,12,opt,name=pwd_expiry_time,json=pwdExpiryTime,proto3" json:"pwd_expiry_time,omitempty"`
	PwdLifeInDays        int32                `protobuf:"varint,13,opt,name=pwd_life_in_days,json=pwdLifeInDays,proto3" json:"pwd_life_in_days,omitempty"`
	ForcePwdChange       bool                 `protobuf:"varint,14,opt,name=force_pwd_change,json=forcePwdChange,proto3" json:"force_pwd_change,omitempty"`
	InstitutionId        string               `protobuf:"bytes,15,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	BXX_UpdatedFields    []string             `protobuf:"bytes,16,rep,name=BXX__updated_fields,json=BXXUpdatedFields,proto3" json:"BXX__updated_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *AdminUser) Reset()         { *m = AdminUser{} }
func (m *AdminUser) String() string { return proto.CompactTextString(m) }
func (*AdminUser) ProtoMessage()    {}
func (*AdminUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{3}
}

func (m *AdminUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUser.Unmarshal(m, b)
}
func (m *AdminUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUser.Marshal(b, m, deterministic)
}
func (m *AdminUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUser.Merge(m, src)
}
func (m *AdminUser) XXX_Size() int {
	return xxx_messageInfo_AdminUser.Size(m)
}
func (m *AdminUser) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUser.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUser proto.InternalMessageInfo

func (m *AdminUser) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AdminUser) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AdminUser) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AdminUser) GetFullname() string {
	if m != nil {
		return m.Fullname
	}
	return ""
}

func (m *AdminUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AdminUser) GetAccountAccess() bool {
	if m != nil {
		return m.AccountAccess
	}
	return false
}

func (m *AdminUser) GetLoginCounter() int32 {
	if m != nil {
		return m.LoginCounter
	}
	return 0
}

func (m *AdminUser) GetLastLogin() *timestamp.Timestamp {
	if m != nil {
		return m.LastLogin
	}
	return nil
}

func (m *AdminUser) GetAccountExpiry() *timestamp.Timestamp {
	if m != nil {
		return m.AccountExpiry
	}
	return nil
}

func (m *AdminUser) GetPhoto() string {
	if m != nil {
		return m.Photo
	}
	return ""
}

func (m *AdminUser) GetPwdExpiry() bool {
	if m != nil {
		return m.PwdExpiry
	}
	return false
}

func (m *AdminUser) GetPwdExpiryTime() *timestamp.Timestamp {
	if m != nil {
		return m.PwdExpiryTime
	}
	return nil
}

func (m *AdminUser) GetPwdLifeInDays() int32 {
	if m != nil {
		return m.PwdLifeInDays
	}
	return 0
}

func (m *AdminUser) GetForcePwdChange() bool {
	if m != nil {
		return m.ForcePwdChange
	}
	return false
}

func (m *AdminUser) GetInstitutionId() string {
	if m != nil {
		return m.InstitutionId
	}
	return ""
}

func (m *AdminUser) GetBXX_UpdatedFields() []string {
	if m != nil {
		return m.BXX_UpdatedFields
	}
	return nil
}

type AdminUserFindRequest struct {
	Filter               string         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AdminUserFindRequest) Reset()         { *m = AdminUserFindRequest{} }
func (m *AdminUserFindRequest) String() string { return proto.CompactTextString(m) }
func (*AdminUserFindRequest) ProtoMessage()    {}
func (*AdminUserFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{4}
}

func (m *AdminUserFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserFindRequest.Unmarshal(m, b)
}
func (m *AdminUserFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserFindRequest.Marshal(b, m, deterministic)
}
func (m *AdminUserFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserFindRequest.Merge(m, src)
}
func (m *AdminUserFindRequest) XXX_Size() int {
	return xxx_messageInfo_AdminUserFindRequest.Size(m)
}
func (m *AdminUserFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserFindRequest proto.InternalMessageInfo

func (m *AdminUserFindRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *AdminUserFindRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AdminUserFindResponse struct {
	AdminUsers           []*AdminUser `protobuf:"bytes,1,rep,name=adminUsers,proto3" json:"adminUsers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *AdminUserFindResponse) Reset()         { *m = AdminUserFindResponse{} }
func (m *AdminUserFindResponse) String() string { return proto.CompactTextString(m) }
func (*AdminUserFindResponse) ProtoMessage()    {}
func (*AdminUserFindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{5}
}

func (m *AdminUserFindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserFindResponse.Unmarshal(m, b)
}
func (m *AdminUserFindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserFindResponse.Marshal(b, m, deterministic)
}
func (m *AdminUserFindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserFindResponse.Merge(m, src)
}
func (m *AdminUserFindResponse) XXX_Size() int {
	return xxx_messageInfo_AdminUserFindResponse.Size(m)
}
func (m *AdminUserFindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserFindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserFindResponse proto.InternalMessageInfo

func (m *AdminUserFindResponse) GetAdminUsers() []*AdminUser {
	if m != nil {
		return m.AdminUsers
	}
	return nil
}

type AdminUserFindOneRequest struct {
	Filter               string         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AdminUserFindOneRequest) Reset()         { *m = AdminUserFindOneRequest{} }
func (m *AdminUserFindOneRequest) String() string { return proto.CompactTextString(m) }
func (*AdminUserFindOneRequest) ProtoMessage()    {}
func (*AdminUserFindOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{6}
}

func (m *AdminUserFindOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserFindOneRequest.Unmarshal(m, b)
}
func (m *AdminUserFindOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserFindOneRequest.Marshal(b, m, deterministic)
}
func (m *AdminUserFindOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserFindOneRequest.Merge(m, src)
}
func (m *AdminUserFindOneRequest) XXX_Size() int {
	return xxx_messageInfo_AdminUserFindOneRequest.Size(m)
}
func (m *AdminUserFindOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserFindOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserFindOneRequest proto.InternalMessageInfo

func (m *AdminUserFindOneRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *AdminUserFindOneRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AdminUserFindOneResponse struct {
	AdminUser            *AdminUser `protobuf:"bytes,1,opt,name=adminUser,proto3" json:"adminUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AdminUserFindOneResponse) Reset()         { *m = AdminUserFindOneResponse{} }
func (m *AdminUserFindOneResponse) String() string { return proto.CompactTextString(m) }
func (*AdminUserFindOneResponse) ProtoMessage()    {}
func (*AdminUserFindOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{7}
}

func (m *AdminUserFindOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserFindOneResponse.Unmarshal(m, b)
}
func (m *AdminUserFindOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserFindOneResponse.Marshal(b, m, deterministic)
}
func (m *AdminUserFindOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserFindOneResponse.Merge(m, src)
}
func (m *AdminUserFindOneResponse) XXX_Size() int {
	return xxx_messageInfo_AdminUserFindOneResponse.Size(m)
}
func (m *AdminUserFindOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserFindOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserFindOneResponse proto.InternalMessageInfo

func (m *AdminUserFindOneResponse) GetAdminUser() *AdminUser {
	if m != nil {
		return m.AdminUser
	}
	return nil
}

type AdminUserCreateRequest struct {
	AdminUser            *AdminUser     `protobuf:"bytes,1,opt,name=adminUser,proto3" json:"adminUser,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AdminUserCreateRequest) Reset()         { *m = AdminUserCreateRequest{} }
func (m *AdminUserCreateRequest) String() string { return proto.CompactTextString(m) }
func (*AdminUserCreateRequest) ProtoMessage()    {}
func (*AdminUserCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{8}
}

func (m *AdminUserCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserCreateRequest.Unmarshal(m, b)
}
func (m *AdminUserCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserCreateRequest.Marshal(b, m, deterministic)
}
func (m *AdminUserCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserCreateRequest.Merge(m, src)
}
func (m *AdminUserCreateRequest) XXX_Size() int {
	return xxx_messageInfo_AdminUserCreateRequest.Size(m)
}
func (m *AdminUserCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserCreateRequest proto.InternalMessageInfo

func (m *AdminUserCreateRequest) GetAdminUser() *AdminUser {
	if m != nil {
		return m.AdminUser
	}
	return nil
}

func (m *AdminUserCreateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AdminUserCreateResponse struct {
	AdminUser            *AdminUser `protobuf:"bytes,1,opt,name=adminUser,proto3" json:"adminUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AdminUserCreateResponse) Reset()         { *m = AdminUserCreateResponse{} }
func (m *AdminUserCreateResponse) String() string { return proto.CompactTextString(m) }
func (*AdminUserCreateResponse) ProtoMessage()    {}
func (*AdminUserCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{9}
}

func (m *AdminUserCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserCreateResponse.Unmarshal(m, b)
}
func (m *AdminUserCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserCreateResponse.Marshal(b, m, deterministic)
}
func (m *AdminUserCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserCreateResponse.Merge(m, src)
}
func (m *AdminUserCreateResponse) XXX_Size() int {
	return xxx_messageInfo_AdminUserCreateResponse.Size(m)
}
func (m *AdminUserCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserCreateResponse proto.InternalMessageInfo

func (m *AdminUserCreateResponse) GetAdminUser() *AdminUser {
	if m != nil {
		return m.AdminUser
	}
	return nil
}

type AdminUserFindByIdRequest struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filter               string         `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AdminUserFindByIdRequest) Reset()         { *m = AdminUserFindByIdRequest{} }
func (m *AdminUserFindByIdRequest) String() string { return proto.CompactTextString(m) }
func (*AdminUserFindByIdRequest) ProtoMessage()    {}
func (*AdminUserFindByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{10}
}

func (m *AdminUserFindByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserFindByIdRequest.Unmarshal(m, b)
}
func (m *AdminUserFindByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserFindByIdRequest.Marshal(b, m, deterministic)
}
func (m *AdminUserFindByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserFindByIdRequest.Merge(m, src)
}
func (m *AdminUserFindByIdRequest) XXX_Size() int {
	return xxx_messageInfo_AdminUserFindByIdRequest.Size(m)
}
func (m *AdminUserFindByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserFindByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserFindByIdRequest proto.InternalMessageInfo

func (m *AdminUserFindByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AdminUserFindByIdRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *AdminUserFindByIdRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AdminUserFindByIdResponse struct {
	AdminUser            *AdminUser `protobuf:"bytes,1,opt,name=adminUser,proto3" json:"adminUser,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AdminUserFindByIdResponse) Reset()         { *m = AdminUserFindByIdResponse{} }
func (m *AdminUserFindByIdResponse) String() string { return proto.CompactTextString(m) }
func (*AdminUserFindByIdResponse) ProtoMessage()    {}
func (*AdminUserFindByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{11}
}

func (m *AdminUserFindByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserFindByIdResponse.Unmarshal(m, b)
}
func (m *AdminUserFindByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserFindByIdResponse.Marshal(b, m, deterministic)
}
func (m *AdminUserFindByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserFindByIdResponse.Merge(m, src)
}
func (m *AdminUserFindByIdResponse) XXX_Size() int {
	return xxx_messageInfo_AdminUserFindByIdResponse.Size(m)
}
func (m *AdminUserFindByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserFindByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserFindByIdResponse proto.InternalMessageInfo

func (m *AdminUserFindByIdResponse) GetAdminUser() *AdminUser {
	if m != nil {
		return m.AdminUser
	}
	return nil
}

type AdminUserCountRequest struct {
	Filter               string         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AdminUserCountRequest) Reset()         { *m = AdminUserCountRequest{} }
func (m *AdminUserCountRequest) String() string { return proto.CompactTextString(m) }
func (*AdminUserCountRequest) ProtoMessage()    {}
func (*AdminUserCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{12}
}

func (m *AdminUserCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserCountRequest.Unmarshal(m, b)
}
func (m *AdminUserCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserCountRequest.Marshal(b, m, deterministic)
}
func (m *AdminUserCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserCountRequest.Merge(m, src)
}
func (m *AdminUserCountRequest) XXX_Size() int {
	return xxx_messageInfo_AdminUserCountRequest.Size(m)
}
func (m *AdminUserCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserCountRequest proto.InternalMessageInfo

func (m *AdminUserCountRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *AdminUserCountRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AdminUserCountResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminUserCountResponse) Reset()         { *m = AdminUserCountResponse{} }
func (m *AdminUserCountResponse) String() string { return proto.CompactTextString(m) }
func (*AdminUserCountResponse) ProtoMessage()    {}
func (*AdminUserCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{13}
}

func (m *AdminUserCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserCountResponse.Unmarshal(m, b)
}
func (m *AdminUserCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserCountResponse.Marshal(b, m, deterministic)
}
func (m *AdminUserCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserCountResponse.Merge(m, src)
}
func (m *AdminUserCountResponse) XXX_Size() int {
	return xxx_messageInfo_AdminUserCountResponse.Size(m)
}
func (m *AdminUserCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserCountResponse proto.InternalMessageInfo

func (m *AdminUserCountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type AdminUserUpdateRequest struct {
	Where                string         `protobuf:"bytes,1,opt,name=where,proto3" json:"where,omitempty"`
	AdminUser            *AdminUser     `protobuf:"bytes,2,opt,name=adminUser,proto3" json:"adminUser,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AdminUserUpdateRequest) Reset()         { *m = AdminUserUpdateRequest{} }
func (m *AdminUserUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*AdminUserUpdateRequest) ProtoMessage()    {}
func (*AdminUserUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{14}
}

func (m *AdminUserUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserUpdateRequest.Unmarshal(m, b)
}
func (m *AdminUserUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserUpdateRequest.Marshal(b, m, deterministic)
}
func (m *AdminUserUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserUpdateRequest.Merge(m, src)
}
func (m *AdminUserUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_AdminUserUpdateRequest.Size(m)
}
func (m *AdminUserUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserUpdateRequest proto.InternalMessageInfo

func (m *AdminUserUpdateRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

func (m *AdminUserUpdateRequest) GetAdminUser() *AdminUser {
	if m != nil {
		return m.AdminUser
	}
	return nil
}

func (m *AdminUserUpdateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AdminUserUpdateResponse struct {
	Updated              bool     `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminUserUpdateResponse) Reset()         { *m = AdminUserUpdateResponse{} }
func (m *AdminUserUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*AdminUserUpdateResponse) ProtoMessage()    {}
func (*AdminUserUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{15}
}

func (m *AdminUserUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserUpdateResponse.Unmarshal(m, b)
}
func (m *AdminUserUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserUpdateResponse.Marshal(b, m, deterministic)
}
func (m *AdminUserUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserUpdateResponse.Merge(m, src)
}
func (m *AdminUserUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_AdminUserUpdateResponse.Size(m)
}
func (m *AdminUserUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserUpdateResponse proto.InternalMessageInfo

func (m *AdminUserUpdateResponse) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

type AdminUserDeleteByIdRequest struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AdminUserDeleteByIdRequest) Reset()         { *m = AdminUserDeleteByIdRequest{} }
func (m *AdminUserDeleteByIdRequest) String() string { return proto.CompactTextString(m) }
func (*AdminUserDeleteByIdRequest) ProtoMessage()    {}
func (*AdminUserDeleteByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{16}
}

func (m *AdminUserDeleteByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserDeleteByIdRequest.Unmarshal(m, b)
}
func (m *AdminUserDeleteByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserDeleteByIdRequest.Marshal(b, m, deterministic)
}
func (m *AdminUserDeleteByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserDeleteByIdRequest.Merge(m, src)
}
func (m *AdminUserDeleteByIdRequest) XXX_Size() int {
	return xxx_messageInfo_AdminUserDeleteByIdRequest.Size(m)
}
func (m *AdminUserDeleteByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserDeleteByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserDeleteByIdRequest proto.InternalMessageInfo

func (m *AdminUserDeleteByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AdminUserDeleteByIdRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AdminUserDeleteByIdResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminUserDeleteByIdResponse) Reset()         { *m = AdminUserDeleteByIdResponse{} }
func (m *AdminUserDeleteByIdResponse) String() string { return proto.CompactTextString(m) }
func (*AdminUserDeleteByIdResponse) ProtoMessage()    {}
func (*AdminUserDeleteByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{17}
}

func (m *AdminUserDeleteByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserDeleteByIdResponse.Unmarshal(m, b)
}
func (m *AdminUserDeleteByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserDeleteByIdResponse.Marshal(b, m, deterministic)
}
func (m *AdminUserDeleteByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserDeleteByIdResponse.Merge(m, src)
}
func (m *AdminUserDeleteByIdResponse) XXX_Size() int {
	return xxx_messageInfo_AdminUserDeleteByIdResponse.Size(m)
}
func (m *AdminUserDeleteByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserDeleteByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserDeleteByIdResponse proto.InternalMessageInfo

func (m *AdminUserDeleteByIdResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type AdminUserDeleteWithWhereRequest struct {
	Where                string         `protobuf:"bytes,1,opt,name=where,proto3" json:"where,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AdminUserDeleteWithWhereRequest) Reset()         { *m = AdminUserDeleteWithWhereRequest{} }
func (m *AdminUserDeleteWithWhereRequest) String() string { return proto.CompactTextString(m) }
func (*AdminUserDeleteWithWhereRequest) ProtoMessage()    {}
func (*AdminUserDeleteWithWhereRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{18}
}

func (m *AdminUserDeleteWithWhereRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserDeleteWithWhereRequest.Unmarshal(m, b)
}
func (m *AdminUserDeleteWithWhereRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserDeleteWithWhereRequest.Marshal(b, m, deterministic)
}
func (m *AdminUserDeleteWithWhereRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserDeleteWithWhereRequest.Merge(m, src)
}
func (m *AdminUserDeleteWithWhereRequest) XXX_Size() int {
	return xxx_messageInfo_AdminUserDeleteWithWhereRequest.Size(m)
}
func (m *AdminUserDeleteWithWhereRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserDeleteWithWhereRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserDeleteWithWhereRequest proto.InternalMessageInfo

func (m *AdminUserDeleteWithWhereRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

func (m *AdminUserDeleteWithWhereRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AdminUserDeleteWithWhereResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AdminUserDeleteWithWhereResponse) Reset()         { *m = AdminUserDeleteWithWhereResponse{} }
func (m *AdminUserDeleteWithWhereResponse) String() string { return proto.CompactTextString(m) }
func (*AdminUserDeleteWithWhereResponse) ProtoMessage()    {}
func (*AdminUserDeleteWithWhereResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{19}
}

func (m *AdminUserDeleteWithWhereResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AdminUserDeleteWithWhereResponse.Unmarshal(m, b)
}
func (m *AdminUserDeleteWithWhereResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AdminUserDeleteWithWhereResponse.Marshal(b, m, deterministic)
}
func (m *AdminUserDeleteWithWhereResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AdminUserDeleteWithWhereResponse.Merge(m, src)
}
func (m *AdminUserDeleteWithWhereResponse) XXX_Size() int {
	return xxx_messageInfo_AdminUserDeleteWithWhereResponse.Size(m)
}
func (m *AdminUserDeleteWithWhereResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AdminUserDeleteWithWhereResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AdminUserDeleteWithWhereResponse proto.InternalMessageInfo

func (m *AdminUserDeleteWithWhereResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

// ----------------------------------------
// AuthRole Model
// ----------------------------------------
type AuthRole struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description          string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Default              bool     `protobuf:"varint,4,opt,name=default,proto3" json:"default,omitempty"`
	Status               bool     `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthRole) Reset()         { *m = AuthRole{} }
func (m *AuthRole) String() string { return proto.CompactTextString(m) }
func (*AuthRole) ProtoMessage()    {}
func (*AuthRole) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{20}
}

func (m *AuthRole) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthRole.Unmarshal(m, b)
}
func (m *AuthRole) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthRole.Marshal(b, m, deterministic)
}
func (m *AuthRole) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthRole.Merge(m, src)
}
func (m *AuthRole) XXX_Size() int {
	return xxx_messageInfo_AuthRole.Size(m)
}
func (m *AuthRole) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthRole.DiscardUnknown(m)
}

var xxx_messageInfo_AuthRole proto.InternalMessageInfo

func (m *AuthRole) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AuthRole) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AuthRole) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *AuthRole) GetDefault() bool {
	if m != nil {
		return m.Default
	}
	return false
}

func (m *AuthRole) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

// ----------------------------------------
// Auth Model
// ----------------------------------------
type AuthLoginRequest struct {
	Username             string         `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string         `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AuthLoginRequest) Reset()         { *m = AuthLoginRequest{} }
func (m *AuthLoginRequest) String() string { return proto.CompactTextString(m) }
func (*AuthLoginRequest) ProtoMessage()    {}
func (*AuthLoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{21}
}

func (m *AuthLoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLoginRequest.Unmarshal(m, b)
}
func (m *AuthLoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLoginRequest.Marshal(b, m, deterministic)
}
func (m *AuthLoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLoginRequest.Merge(m, src)
}
func (m *AuthLoginRequest) XXX_Size() int {
	return xxx_messageInfo_AuthLoginRequest.Size(m)
}
func (m *AuthLoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLoginRequest proto.InternalMessageInfo

func (m *AuthLoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *AuthLoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *AuthLoginRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AuthLoginResponse struct {
	Token                string      `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	UserId               string      `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Roles                []*AuthRole `protobuf:"bytes,3,rep,name=roles,proto3" json:"roles,omitempty"`
	ForcePwdChange       bool        `protobuf:"varint,4,opt,name=force_pwd_change,json=forcePwdChange,proto3" json:"force_pwd_change,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *AuthLoginResponse) Reset()         { *m = AuthLoginResponse{} }
func (m *AuthLoginResponse) String() string { return proto.CompactTextString(m) }
func (*AuthLoginResponse) ProtoMessage()    {}
func (*AuthLoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{22}
}

func (m *AuthLoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLoginResponse.Unmarshal(m, b)
}
func (m *AuthLoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLoginResponse.Marshal(b, m, deterministic)
}
func (m *AuthLoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLoginResponse.Merge(m, src)
}
func (m *AuthLoginResponse) XXX_Size() int {
	return xxx_messageInfo_AuthLoginResponse.Size(m)
}
func (m *AuthLoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLoginResponse proto.InternalMessageInfo

func (m *AuthLoginResponse) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthLoginResponse) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthLoginResponse) GetRoles() []*AuthRole {
	if m != nil {
		return m.Roles
	}
	return nil
}

func (m *AuthLoginResponse) GetForcePwdChange() bool {
	if m != nil {
		return m.ForcePwdChange
	}
	return false
}

type AuthLogoutRequest struct {
	Token                string         `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AuthLogoutRequest) Reset()         { *m = AuthLogoutRequest{} }
func (m *AuthLogoutRequest) String() string { return proto.CompactTextString(m) }
func (*AuthLogoutRequest) ProtoMessage()    {}
func (*AuthLogoutRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{23}
}

func (m *AuthLogoutRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLogoutRequest.Unmarshal(m, b)
}
func (m *AuthLogoutRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLogoutRequest.Marshal(b, m, deterministic)
}
func (m *AuthLogoutRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLogoutRequest.Merge(m, src)
}
func (m *AuthLogoutRequest) XXX_Size() int {
	return xxx_messageInfo_AuthLogoutRequest.Size(m)
}
func (m *AuthLogoutRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLogoutRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLogoutRequest proto.InternalMessageInfo

func (m *AuthLogoutRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthLogoutRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AuthLogoutResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthLogoutResponse) Reset()         { *m = AuthLogoutResponse{} }
func (m *AuthLogoutResponse) String() string { return proto.CompactTextString(m) }
func (*AuthLogoutResponse) ProtoMessage()    {}
func (*AuthLogoutResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{24}
}

func (m *AuthLogoutResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthLogoutResponse.Unmarshal(m, b)
}
func (m *AuthLogoutResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthLogoutResponse.Marshal(b, m, deterministic)
}
func (m *AuthLogoutResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthLogoutResponse.Merge(m, src)
}
func (m *AuthLogoutResponse) XXX_Size() int {
	return xxx_messageInfo_AuthLogoutResponse.Size(m)
}
func (m *AuthLogoutResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthLogoutResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthLogoutResponse proto.InternalMessageInfo

func (m *AuthLogoutResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AuthResetPasswordRequest struct {
	OldPassword          string         `protobuf:"bytes,1,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword          string         `protobuf:"bytes,2,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AuthResetPasswordRequest) Reset()         { *m = AuthResetPasswordRequest{} }
func (m *AuthResetPasswordRequest) String() string { return proto.CompactTextString(m) }
func (*AuthResetPasswordRequest) ProtoMessage()    {}
func (*AuthResetPasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{25}
}

func (m *AuthResetPasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResetPasswordRequest.Unmarshal(m, b)
}
func (m *AuthResetPasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResetPasswordRequest.Marshal(b, m, deterministic)
}
func (m *AuthResetPasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResetPasswordRequest.Merge(m, src)
}
func (m *AuthResetPasswordRequest) XXX_Size() int {
	return xxx_messageInfo_AuthResetPasswordRequest.Size(m)
}
func (m *AuthResetPasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResetPasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResetPasswordRequest proto.InternalMessageInfo

func (m *AuthResetPasswordRequest) GetOldPassword() string {
	if m != nil {
		return m.OldPassword
	}
	return ""
}

func (m *AuthResetPasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *AuthResetPasswordRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AuthResetPasswordResponse struct {
	Message              string   `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthResetPasswordResponse) Reset()         { *m = AuthResetPasswordResponse{} }
func (m *AuthResetPasswordResponse) String() string { return proto.CompactTextString(m) }
func (*AuthResetPasswordResponse) ProtoMessage()    {}
func (*AuthResetPasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{26}
}

func (m *AuthResetPasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthResetPasswordResponse.Unmarshal(m, b)
}
func (m *AuthResetPasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthResetPasswordResponse.Marshal(b, m, deterministic)
}
func (m *AuthResetPasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthResetPasswordResponse.Merge(m, src)
}
func (m *AuthResetPasswordResponse) XXX_Size() int {
	return xxx_messageInfo_AuthResetPasswordResponse.Size(m)
}
func (m *AuthResetPasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthResetPasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthResetPasswordResponse proto.InternalMessageInfo

func (m *AuthResetPasswordResponse) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type AuthorisationRequest struct {
	UserId               string         `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Token                string         `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *AuthorisationRequest) Reset()         { *m = AuthorisationRequest{} }
func (m *AuthorisationRequest) String() string { return proto.CompactTextString(m) }
func (*AuthorisationRequest) ProtoMessage()    {}
func (*AuthorisationRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{27}
}

func (m *AuthorisationRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorisationRequest.Unmarshal(m, b)
}
func (m *AuthorisationRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorisationRequest.Marshal(b, m, deterministic)
}
func (m *AuthorisationRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorisationRequest.Merge(m, src)
}
func (m *AuthorisationRequest) XXX_Size() int {
	return xxx_messageInfo_AuthorisationRequest.Size(m)
}
func (m *AuthorisationRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorisationRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorisationRequest proto.InternalMessageInfo

func (m *AuthorisationRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *AuthorisationRequest) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *AuthorisationRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type AuthorisationResponse struct {
	Authorised           bool     `protobuf:"varint,1,opt,name=authorised,proto3" json:"authorised,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AuthorisationResponse) Reset()         { *m = AuthorisationResponse{} }
func (m *AuthorisationResponse) String() string { return proto.CompactTextString(m) }
func (*AuthorisationResponse) ProtoMessage()    {}
func (*AuthorisationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_dfeac6748badcf6d, []int{28}
}

func (m *AuthorisationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AuthorisationResponse.Unmarshal(m, b)
}
func (m *AuthorisationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AuthorisationResponse.Marshal(b, m, deterministic)
}
func (m *AuthorisationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AuthorisationResponse.Merge(m, src)
}
func (m *AuthorisationResponse) XXX_Size() int {
	return xxx_messageInfo_AuthorisationResponse.Size(m)
}
func (m *AuthorisationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AuthorisationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AuthorisationResponse proto.InternalMessageInfo

func (m *AuthorisationResponse) GetAuthorised() bool {
	if m != nil {
		return m.Authorised
	}
	return false
}

func init() {
	proto.RegisterEnum("pbx.HealthCheckResponse_ServingStatus", HealthCheckResponse_ServingStatus_name, HealthCheckResponse_ServingStatus_value)
	proto.RegisterType((*Empty)(nil), "pbx.Empty")
	proto.RegisterType((*HealthCheckRequest)(nil), "pbx.HealthCheckRequest")
	proto.RegisterType((*HealthCheckResponse)(nil), "pbx.HealthCheckResponse")
	proto.RegisterType((*AdminUser)(nil), "pbx.AdminUser")
	proto.RegisterType((*AdminUserFindRequest)(nil), "pbx.AdminUserFindRequest")
	proto.RegisterType((*AdminUserFindResponse)(nil), "pbx.AdminUserFindResponse")
	proto.RegisterType((*AdminUserFindOneRequest)(nil), "pbx.AdminUserFindOneRequest")
	proto.RegisterType((*AdminUserFindOneResponse)(nil), "pbx.AdminUserFindOneResponse")
	proto.RegisterType((*AdminUserCreateRequest)(nil), "pbx.AdminUserCreateRequest")
	proto.RegisterType((*AdminUserCreateResponse)(nil), "pbx.AdminUserCreateResponse")
	proto.RegisterType((*AdminUserFindByIdRequest)(nil), "pbx.AdminUserFindByIdRequest")
	proto.RegisterType((*AdminUserFindByIdResponse)(nil), "pbx.AdminUserFindByIdResponse")
	proto.RegisterType((*AdminUserCountRequest)(nil), "pbx.AdminUserCountRequest")
	proto.RegisterType((*AdminUserCountResponse)(nil), "pbx.AdminUserCountResponse")
	proto.RegisterType((*AdminUserUpdateRequest)(nil), "pbx.AdminUserUpdateRequest")
	proto.RegisterType((*AdminUserUpdateResponse)(nil), "pbx.AdminUserUpdateResponse")
	proto.RegisterType((*AdminUserDeleteByIdRequest)(nil), "pbx.AdminUserDeleteByIdRequest")
	proto.RegisterType((*AdminUserDeleteByIdResponse)(nil), "pbx.AdminUserDeleteByIdResponse")
	proto.RegisterType((*AdminUserDeleteWithWhereRequest)(nil), "pbx.AdminUserDeleteWithWhereRequest")
	proto.RegisterType((*AdminUserDeleteWithWhereResponse)(nil), "pbx.AdminUserDeleteWithWhereResponse")
	proto.RegisterType((*AuthRole)(nil), "pbx.AuthRole")
	proto.RegisterType((*AuthLoginRequest)(nil), "pbx.AuthLoginRequest")
	proto.RegisterType((*AuthLoginResponse)(nil), "pbx.AuthLoginResponse")
	proto.RegisterType((*AuthLogoutRequest)(nil), "pbx.AuthLogoutRequest")
	proto.RegisterType((*AuthLogoutResponse)(nil), "pbx.AuthLogoutResponse")
	proto.RegisterType((*AuthResetPasswordRequest)(nil), "pbx.AuthResetPasswordRequest")
	proto.RegisterType((*AuthResetPasswordResponse)(nil), "pbx.AuthResetPasswordResponse")
	proto.RegisterType((*AuthorisationRequest)(nil), "pbx.AuthorisationRequest")
	proto.RegisterType((*AuthorisationResponse)(nil), "pbx.AuthorisationResponse")
}

func init() { proto.RegisterFile("pbx/iam.proto", fileDescriptor_dfeac6748badcf6d) }

var fileDescriptor_dfeac6748badcf6d = []byte{
	// 1323 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0x4b, 0x6f, 0xdb, 0x46,
	0x10, 0x0e, 0x25, 0xcb, 0xb6, 0x46, 0x91, 0xac, 0x6e, 0x94, 0x98, 0x61, 0x5e, 0x2a, 0xd3, 0xb4,
	0x42, 0xd1, 0x2a, 0x85, 0x83, 0xa2, 0x68, 0x90, 0x16, 0xf0, 0x23, 0x0f, 0xa1, 0x81, 0x1d, 0xd0,
	0x71, 0x2d, 0xb4, 0x28, 0x08, 0x9a, 0x5c, 0x49, 0x44, 0x28, 0x92, 0xe5, 0xae, 0x22, 0xfb, 0xda,
	0x53, 0x0f, 0xbd, 0xe4, 0x37, 0xf5, 0x17, 0xf5, 0x1f, 0x14, 0xfb, 0x20, 0x45, 0x52, 0x94, 0x15,
	0x19, 0xb9, 0x69, 0x9e, 0xfb, 0x71, 0x66, 0x76, 0xe7, 0x13, 0xd4, 0xc3, 0xb3, 0xf3, 0xc7, 0xae,
	0x35, 0xee, 0x86, 0x51, 0x40, 0x03, 0x54, 0x0e, 0xcf, 0xce, 0xb5, 0x26, 0xd3, 0xd9, 0xc1, 0x78,
	0x1c, 0xf8, 0x42, 0xad, 0x3d, 0x18, 0x06, 0xc1, 0xd0, 0xc3, 0x8f, 0xb9, 0x74, 0x36, 0x19, 0x3c,
	0xa6, 0xee, 0x18, 0x13, 0x6a, 0x8d, 0x43, 0xe1, 0xa0, 0x6f, 0x40, 0xe5, 0xf9, 0x38, 0xa4, 0x17,
	0x7a, 0x17, 0xd0, 0x2b, 0x6c, 0x79, 0x74, 0xb4, 0x3f, 0xc2, 0xf6, 0x3b, 0x03, 0xff, 0x39, 0xc1,
	0x84, 0x22, 0x15, 0x36, 0x08, 0x8e, 0xde, 0xbb, 0x36, 0x56, 0x95, 0xb6, 0xd2, 0xa9, 0x1a, 0xb1,
	0xa8, 0x7f, 0x50, 0xe0, 0x46, 0x26, 0x80, 0x84, 0x81, 0x4f, 0x30, 0xfa, 0x19, 0xd6, 0x09, 0xb5,
	0xe8, 0x84, 0xf0, 0x80, 0xc6, 0xce, 0x97, 0xdd, 0xf0, 0xec, 0xbc, 0x5b, 0xe0, 0xd9, 0x3d, 0x66,
	0x99, 0xfc, 0xe1, 0x31, 0xf7, 0x36, 0x64, 0x94, 0xfe, 0x14, 0xea, 0x19, 0x03, 0xaa, 0xc1, 0xc6,
	0xc9, 0xe1, 0x2f, 0x87, 0x47, 0xa7, 0x87, 0xcd, 0x6b, 0x4c, 0x38, 0x7e, 0x6e, 0xfc, 0xda, 0x3b,
	0x7c, 0xd9, 0x54, 0xd0, 0x16, 0xd4, 0x0e, 0x8f, 0xde, 0x9a, 0xb1, 0xa2, 0xa4, 0xff, 0xb7, 0x06,
	0xd5, 0x5d, 0x67, 0xec, 0xfa, 0x27, 0x04, 0x47, 0xa8, 0x01, 0x25, 0xd7, 0x91, 0xb0, 0x4b, 0xae,
	0x83, 0x34, 0xd8, 0x9c, 0x10, 0x1c, 0xf9, 0xd6, 0x18, 0xab, 0x25, 0xae, 0x4d, 0x64, 0x66, 0x0b,
	0x2d, 0x42, 0xa6, 0x41, 0xe4, 0xa8, 0x65, 0x61, 0x8b, 0x65, 0x66, 0x1b, 0x4c, 0x3c, 0x8f, 0xc7,
	0xad, 0x09, 0x5b, 0x2c, 0xa3, 0x16, 0x54, 0xf0, 0xd8, 0x72, 0x3d, 0xb5, 0xc2, 0x0d, 0x42, 0x40,
	0x8f, 0xa0, 0x61, 0xd9, 0x76, 0x30, 0xf1, 0xa9, 0x69, 0xd9, 0x36, 0x26, 0x44, 0x5d, 0x6f, 0x2b,
	0x9d, 0x4d, 0xa3, 0x2e, 0xb5, 0xbb, 0x5c, 0x89, 0x1e, 0x42, 0xdd, 0x0b, 0x86, 0xae, 0x6f, 0x72,
	0x25, 0x8e, 0xd4, 0x8d, 0xb6, 0xd2, 0xa9, 0x18, 0xd7, 0xb9, 0x72, 0x5f, 0xe8, 0xd0, 0x8f, 0x00,
	0x9e, 0x45, 0xa8, 0xc9, 0x95, 0xea, 0x66, 0x5b, 0xe9, 0xd4, 0x76, 0xb4, 0xae, 0x68, 0x6b, 0x37,
	0x6e, 0x6b, 0xf7, 0x6d, 0xdc, 0x56, 0xa3, 0xca, 0xbc, 0x5f, 0x33, 0x67, 0xb4, 0x3b, 0x83, 0x81,
	0xcf, 0x43, 0x37, 0xba, 0x50, 0xab, 0x4b, 0xc3, 0x63, 0x88, 0xcf, 0x79, 0x00, 0xfb, 0xbe, 0x70,
	0x14, 0xd0, 0x40, 0x05, 0xf1, 0x7d, 0x5c, 0x40, 0xf7, 0x00, 0xc2, 0xa9, 0x13, 0x27, 0xad, 0xf1,
	0x6f, 0xab, 0x86, 0x53, 0x47, 0x06, 0xed, 0xc1, 0xd6, 0xcc, 0x6c, 0xb2, 0x89, 0x53, 0xaf, 0x2f,
	0x3f, 0x38, 0x89, 0x67, 0x3a, 0xf4, 0x15, 0x34, 0x59, 0x0e, 0xcf, 0x1d, 0x60, 0xd3, 0xf5, 0x4d,
	0xc7, 0xba, 0x20, 0x6a, 0x9d, 0x97, 0x87, 0x39, 0xbe, 0x76, 0x07, 0xb8, 0xe7, 0x1f, 0x58, 0x17,
	0x04, 0x75, 0xa0, 0x39, 0x08, 0x22, 0x1b, 0x9b, 0xcc, 0xdd, 0x1e, 0x59, 0xfe, 0x10, 0xab, 0x0d,
	0x8e, 0xa8, 0xc1, 0xf5, 0x6f, 0xa6, 0xce, 0x3e, 0xd7, 0xb2, 0xae, 0xb8, 0x3e, 0xa1, 0x2e, 0x9d,
	0x50, 0x37, 0xf0, 0x4d, 0xd7, 0x51, 0xb7, 0xf8, 0x47, 0xd5, 0x53, 0xda, 0x9e, 0x83, 0xbe, 0x85,
	0x1b, 0x7b, 0xfd, 0xbe, 0x69, 0x4e, 0x42, 0xc7, 0xa2, 0xd8, 0x31, 0x07, 0x2e, 0xf6, 0x1c, 0xa2,
	0x36, 0xdb, 0xe5, 0x4e, 0xd5, 0x68, 0xee, 0xf5, 0xfb, 0x27, 0xc2, 0xf0, 0x82, 0xeb, 0xf5, 0xdf,
	0xa0, 0x95, 0x8c, 0xdc, 0x0b, 0xd7, 0x77, 0xe2, 0x9b, 0x73, 0x0b, 0xd6, 0x07, 0xae, 0xc7, 0xba,
	0x2a, 0x26, 0x50, 0x4a, 0xe8, 0x6b, 0x58, 0x1f, 0x61, 0xcb, 0xc1, 0x11, 0x9f, 0xc1, 0xda, 0x0e,
	0xe2, 0xf7, 0x43, 0x46, 0xbd, 0xe2, 0x16, 0x43, 0x7a, 0xe8, 0x2f, 0xe1, 0x66, 0x2e, 0xb7, 0xbc,
	0x64, 0x5d, 0x00, 0x2b, 0x36, 0xb0, 0x8b, 0x56, 0xee, 0xd4, 0x76, 0x1a, 0x3c, 0x51, 0xe2, 0x6f,
	0xa4, 0x3c, 0xf4, 0x3f, 0x60, 0x3b, 0x93, 0xe8, 0xc8, 0xc7, 0x9f, 0x12, 0xe7, 0x2b, 0x50, 0xe7,
	0xd3, 0x4b, 0xa8, 0xdf, 0x40, 0x35, 0x01, 0xc2, 0x8f, 0x98, 0x47, 0x3a, 0x73, 0xd0, 0x23, 0xb8,
	0x95, 0xe8, 0xf7, 0x23, 0x6c, 0xd1, 0x04, 0xe7, 0x4a, 0x79, 0x56, 0xac, 0xf2, 0xf6, 0xdc, 0x99,
	0x57, 0x02, 0xef, 0xe7, 0xca, 0xb0, 0x77, 0xd1, 0x4b, 0xc6, 0x21, 0xff, 0x18, 0xcd, 0xca, 0x5e,
	0x5a, 0x50, 0xf6, 0xf2, 0x52, 0xe0, 0x3d, 0xb8, 0x5d, 0x70, 0xde, 0x95, 0xa0, 0xff, 0x9e, 0x9a,
	0x34, 0xfe, 0xf2, 0x7c, 0xca, 0xf1, 0xe8, 0xa6, 0x9b, 0x2a, 0x92, 0x4b, 0x90, 0x2d, 0xa8, 0xf0,
	0xd7, 0x86, 0x27, 0x2f, 0x1b, 0x42, 0xd0, 0xff, 0x56, 0x52, 0x01, 0xe2, 0xb6, 0xc5, 0x70, 0x5a,
	0x50, 0x99, 0x8e, 0x70, 0x14, 0x6f, 0x23, 0x21, 0x64, 0xbf, 0xb5, 0xf4, 0xf1, 0xb3, 0xb1, 0xbc,
	0xc4, 0x4f, 0x52, 0xb3, 0x11, 0x23, 0x91, 0xd8, 0x55, 0xd8, 0x90, 0x4f, 0x04, 0x07, 0xb3, 0x69,
	0xc4, 0xa2, 0xde, 0x07, 0x2d, 0x09, 0x3a, 0xc0, 0x1e, 0xa6, 0xf8, 0xb2, 0x49, 0x58, 0x05, 0xce,
	0x0f, 0x70, 0xa7, 0x30, 0xf3, 0x0c, 0x92, 0xc3, 0xb5, 0x09, 0x24, 0x29, 0xea, 0x36, 0x3c, 0xc8,
	0x05, 0x9e, 0xba, 0x74, 0x74, 0xca, 0xaa, 0x77, 0x79, 0x69, 0x57, 0xe9, 0xf3, 0x33, 0x68, 0x2f,
	0x3e, 0x64, 0x29, 0xc4, 0xbf, 0x14, 0xd8, 0xdc, 0x9d, 0xd0, 0x91, 0x11, 0x78, 0x78, 0xae, 0x48,
	0x08, 0xd6, 0x52, 0x7b, 0x9b, 0xff, 0x46, 0x6d, 0xa8, 0x39, 0x98, 0xd8, 0x91, 0x1b, 0xb2, 0x97,
	0x5b, 0xae, 0xed, 0xb4, 0x4a, 0x1c, 0x36, 0xb0, 0x26, 0x1e, 0xe5, 0x8b, 0x9b, 0x1f, 0xc6, 0x45,
	0x36, 0xd6, 0x92, 0xa5, 0x54, 0xb8, 0x21, 0x66, 0x1f, 0xef, 0xa1, 0xc9, 0x30, 0xf0, 0xfd, 0x19,
	0x17, 0x26, 0xcd, 0x1b, 0x94, 0x4b, 0x78, 0x43, 0x29, 0xc7, 0x1b, 0x56, 0x69, 0xec, 0x07, 0x05,
	0x3e, 0x4b, 0x1d, 0x3c, 0xbb, 0x1e, 0x34, 0x78, 0x87, 0xfd, 0xb8, 0x25, 0x5c, 0x40, 0xdb, 0xb0,
	0xc1, 0xce, 0x67, 0x0b, 0x4c, 0xbe, 0x1d, 0x4c, 0xec, 0x39, 0xe8, 0x21, 0x54, 0xa2, 0xc0, 0xc3,
	0x44, 0x2d, 0xf3, 0x85, 0x50, 0x17, 0x57, 0x40, 0x96, 0xd4, 0x10, 0xb6, 0xc2, 0x7d, 0xb9, 0x56,
	0xb4, 0x2f, 0xf5, 0x93, 0x04, 0x52, 0x30, 0xa1, 0xa9, 0x29, 0x29, 0x80, 0xb4, 0xda, 0x6b, 0x80,
	0xd2, 0x69, 0x67, 0x73, 0x31, 0xc6, 0x84, 0x58, 0xc3, 0x84, 0x68, 0x4a, 0x51, 0xff, 0x47, 0x01,
	0x95, 0x7f, 0x04, 0x26, 0x98, 0xbe, 0x91, 0xc5, 0x8d, 0xe1, 0x7c, 0x0e, 0xd7, 0x03, 0xcf, 0x31,
	0x93, 0x1e, 0x88, 0xd8, 0x5a, 0xe0, 0x39, 0xb1, 0x27, 0x73, 0xf1, 0xf1, 0xd4, 0xcc, 0xb5, 0xa9,
	0xe6, 0xe3, 0xe9, 0x9b, 0xab, 0x74, 0xea, 0x7b, 0xb8, 0x5d, 0x80, 0x66, 0xe9, 0x57, 0x84, 0xd0,
	0x62, 0x61, 0x41, 0xe4, 0x12, 0x8b, 0xcd, 0x66, 0xea, 0x7d, 0x15, 0xdd, 0x8b, 0xdf, 0x57, 0xd9,
	0xcb, 0xa4, 0xce, 0xa5, 0xe2, 0x3a, 0x7f, 0xcc, 0x5b, 0x71, 0x33, 0x77, 0xa2, 0x04, 0x79, 0x1f,
	0xc0, 0x92, 0x86, 0xe4, 0x16, 0xa6, 0x34, 0x3b, 0xff, 0x6e, 0x42, 0x73, 0x0f, 0x5b, 0x76, 0xe0,
	0xf7, 0xac, 0xf1, 0xb1, 0xa0, 0xfb, 0xe8, 0x29, 0x54, 0x38, 0x7b, 0x47, 0xdb, 0xf3, 0x7c, 0x9e,
	0x9f, 0xae, 0xa9, 0x8b, 0x88, 0x3e, 0x7a, 0x06, 0x95, 0x53, 0x8b, 0xda, 0xa3, 0x2b, 0xc4, 0x7e,
	0xa7, 0xa0, 0xa7, 0x50, 0x4d, 0x6e, 0x06, 0xba, 0x99, 0xcc, 0x74, 0xfa, 0x8a, 0x6a, 0xb7, 0xf2,
	0x6a, 0x79, 0xf2, 0x4f, 0x00, 0xb3, 0x59, 0x43, 0x19, 0xaf, 0xd9, 0x4c, 0x6b, 0xdb, 0x73, 0x7a,
	0x19, 0x6e, 0x88, 0x1b, 0x90, 0xe9, 0x35, 0xba, 0x37, 0xbb, 0x56, 0x05, 0x13, 0xa9, 0xdd, 0x5f,
	0x64, 0x96, 0x39, 0x8f, 0xa0, 0x25, 0x5d, 0x33, 0xdd, 0x41, 0xb7, 0x93, 0xb8, 0xfc, 0x8c, 0x68,
	0x5a, 0x91, 0x49, 0xa4, 0xd3, 0xaf, 0xa1, 0xd7, 0xb0, 0x95, 0xa3, 0x2f, 0xe8, 0x4e, 0x76, 0xf9,
	0x65, 0x88, 0x94, 0x76, 0xb7, 0xd8, 0x28, 0xe1, 0xbd, 0x80, 0x7a, 0x86, 0x53, 0xc4, 0xb8, 0x0a,
	0x28, 0x6e, 0x8c, 0xab, 0x90, 0xa1, 0x1e, 0x41, 0x33, 0x4f, 0x09, 0xd1, 0xdd, 0x79, 0xff, 0x19,
	0x11, 0xd5, 0xee, 0x2d, 0xb0, 0xa6, 0x7a, 0x91, 0x23, 0x3b, 0x07, 0xa8, 0x20, 0x26, 0xb5, 0x6a,
	0xe3, 0x5e, 0x2c, 0xe4, 0x48, 0x3d, 0x68, 0x64, 0x89, 0x09, 0xca, 0x7d, 0x52, 0x9a, 0x0a, 0x69,
	0x77, 0x0a, 0x6d, 0x32, 0x55, 0xba, 0x0b, 0x82, 0x28, 0xe4, 0xbb, 0x90, 0x21, 0x32, 0xf9, 0x2e,
	0xe4, 0xb8, 0x45, 0x1f, 0x6e, 0xcc, 0xef, 0xf9, 0x03, 0xf4, 0x20, 0x1b, 0x34, 0xc7, 0x2d, 0xb4,
	0xf6, 0x62, 0x07, 0x99, 0x79, 0x98, 0xe2, 0xa8, 0xb9, 0x1d, 0x8d, 0xbe, 0x28, 0x8a, 0xce, 0xf3,
	0x04, 0xed, 0xd1, 0x12, 0x2f, 0x71, 0xd0, 0xd9, 0x3a, 0xff, 0x8f, 0xf7, 0xe4, 0xff, 0x00, 0x00,
	0x00, 0xff, 0xff, 0xd9, 0xc5, 0x08, 0x4d, 0xa8, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BeaconIamServiceClient is the client API for BeaconIamService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BeaconIamServiceClient interface {
	// Health
	Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	Watch(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (BeaconIamService_WatchClient, error)
	// Auth
	AuthLogin(ctx context.Context, in *AuthLoginRequest, opts ...grpc.CallOption) (*AuthLoginResponse, error)
	AuthLogout(ctx context.Context, in *AuthLogoutRequest, opts ...grpc.CallOption) (*AuthLogoutResponse, error)
	AuthResetPassword(ctx context.Context, in *AuthResetPasswordRequest, opts ...grpc.CallOption) (*AuthResetPasswordResponse, error)
	RequestAuthorisation(ctx context.Context, in *AuthorisationRequest, opts ...grpc.CallOption) (*AuthorisationResponse, error)
	// AdminUser
	AdminUserCreate(ctx context.Context, in *AdminUserCreateRequest, opts ...grpc.CallOption) (*AdminUserCreateResponse, error)
	AdminUserFind(ctx context.Context, in *AdminUserFindRequest, opts ...grpc.CallOption) (*AdminUserFindResponse, error)
	AdminUserFindOne(ctx context.Context, in *AdminUserFindOneRequest, opts ...grpc.CallOption) (*AdminUserFindOneResponse, error)
	AdminUserFindByID(ctx context.Context, in *AdminUserFindByIdRequest, opts ...grpc.CallOption) (*AdminUserFindByIdResponse, error)
	AdminUserCount(ctx context.Context, in *AdminUserCountRequest, opts ...grpc.CallOption) (*AdminUserCountResponse, error)
	AdminUserUpdate(ctx context.Context, in *AdminUserUpdateRequest, opts ...grpc.CallOption) (*AdminUserUpdateResponse, error)
	AdminUserDeleteByID(ctx context.Context, in *AdminUserDeleteByIdRequest, opts ...grpc.CallOption) (*AdminUserDeleteByIdResponse, error)
	AdminUserDeleteWithWhere(ctx context.Context, in *AdminUserDeleteWithWhereRequest, opts ...grpc.CallOption) (*AdminUserDeleteWithWhereResponse, error)
}

type beaconIamServiceClient struct {
	cc *grpc.ClientConn
}

func NewBeaconIamServiceClient(cc *grpc.ClientConn) BeaconIamServiceClient {
	return &beaconIamServiceClient{cc}
}

func (c *beaconIamServiceClient) Check(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconIamService/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconIamServiceClient) Watch(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (BeaconIamService_WatchClient, error) {
	stream, err := c.cc.NewStream(ctx, &_BeaconIamService_serviceDesc.Streams[0], "/pbx.BeaconIamService/Watch", opts...)
	if err != nil {
		return nil, err
	}
	x := &beaconIamServiceWatchClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BeaconIamService_WatchClient interface {
	Recv() (*HealthCheckResponse, error)
	grpc.ClientStream
}

type beaconIamServiceWatchClient struct {
	grpc.ClientStream
}

func (x *beaconIamServiceWatchClient) Recv() (*HealthCheckResponse, error) {
	m := new(HealthCheckResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *beaconIamServiceClient) AuthLogin(ctx context.Context, in *AuthLoginRequest, opts ...grpc.CallOption) (*AuthLoginResponse, error) {
	out := new(AuthLoginResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconIamService/AuthLogin", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconIamServiceClient) AuthLogout(ctx context.Context, in *AuthLogoutRequest, opts ...grpc.CallOption) (*AuthLogoutResponse, error) {
	out := new(AuthLogoutResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconIamService/AuthLogout", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconIamServiceClient) AuthResetPassword(ctx context.Context, in *AuthResetPasswordRequest, opts ...grpc.CallOption) (*AuthResetPasswordResponse, error) {
	out := new(AuthResetPasswordResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconIamService/AuthResetPassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconIamServiceClient) RequestAuthorisation(ctx context.Context, in *AuthorisationRequest, opts ...grpc.CallOption) (*AuthorisationResponse, error) {
	out := new(AuthorisationResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconIamService/RequestAuthorisation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconIamServiceClient) AdminUserCreate(ctx context.Context, in *AdminUserCreateRequest, opts ...grpc.CallOption) (*AdminUserCreateResponse, error) {
	out := new(AdminUserCreateResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconIamService/AdminUserCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconIamServiceClient) AdminUserFind(ctx context.Context, in *AdminUserFindRequest, opts ...grpc.CallOption) (*AdminUserFindResponse, error) {
	out := new(AdminUserFindResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconIamService/AdminUserFind", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconIamServiceClient) AdminUserFindOne(ctx context.Context, in *AdminUserFindOneRequest, opts ...grpc.CallOption) (*AdminUserFindOneResponse, error) {
	out := new(AdminUserFindOneResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconIamService/AdminUserFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconIamServiceClient) AdminUserFindByID(ctx context.Context, in *AdminUserFindByIdRequest, opts ...grpc.CallOption) (*AdminUserFindByIdResponse, error) {
	out := new(AdminUserFindByIdResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconIamService/AdminUserFindByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconIamServiceClient) AdminUserCount(ctx context.Context, in *AdminUserCountRequest, opts ...grpc.CallOption) (*AdminUserCountResponse, error) {
	out := new(AdminUserCountResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconIamService/AdminUserCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconIamServiceClient) AdminUserUpdate(ctx context.Context, in *AdminUserUpdateRequest, opts ...grpc.CallOption) (*AdminUserUpdateResponse, error) {
	out := new(AdminUserUpdateResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconIamService/AdminUserUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconIamServiceClient) AdminUserDeleteByID(ctx context.Context, in *AdminUserDeleteByIdRequest, opts ...grpc.CallOption) (*AdminUserDeleteByIdResponse, error) {
	out := new(AdminUserDeleteByIdResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconIamService/AdminUserDeleteByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconIamServiceClient) AdminUserDeleteWithWhere(ctx context.Context, in *AdminUserDeleteWithWhereRequest, opts ...grpc.CallOption) (*AdminUserDeleteWithWhereResponse, error) {
	out := new(AdminUserDeleteWithWhereResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconIamService/AdminUserDeleteWithWhere", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeaconIamServiceServer is the server API for BeaconIamService service.
type BeaconIamServiceServer interface {
	// Health
	Check(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	Watch(*HealthCheckRequest, BeaconIamService_WatchServer) error
	// Auth
	AuthLogin(context.Context, *AuthLoginRequest) (*AuthLoginResponse, error)
	AuthLogout(context.Context, *AuthLogoutRequest) (*AuthLogoutResponse, error)
	AuthResetPassword(context.Context, *AuthResetPasswordRequest) (*AuthResetPasswordResponse, error)
	RequestAuthorisation(context.Context, *AuthorisationRequest) (*AuthorisationResponse, error)
	// AdminUser
	AdminUserCreate(context.Context, *AdminUserCreateRequest) (*AdminUserCreateResponse, error)
	AdminUserFind(context.Context, *AdminUserFindRequest) (*AdminUserFindResponse, error)
	AdminUserFindOne(context.Context, *AdminUserFindOneRequest) (*AdminUserFindOneResponse, error)
	AdminUserFindByID(context.Context, *AdminUserFindByIdRequest) (*AdminUserFindByIdResponse, error)
	AdminUserCount(context.Context, *AdminUserCountRequest) (*AdminUserCountResponse, error)
	AdminUserUpdate(context.Context, *AdminUserUpdateRequest) (*AdminUserUpdateResponse, error)
	AdminUserDeleteByID(context.Context, *AdminUserDeleteByIdRequest) (*AdminUserDeleteByIdResponse, error)
	AdminUserDeleteWithWhere(context.Context, *AdminUserDeleteWithWhereRequest) (*AdminUserDeleteWithWhereResponse, error)
}

// UnimplementedBeaconIamServiceServer can be embedded to have forward compatible implementations.
type UnimplementedBeaconIamServiceServer struct {
}

func (*UnimplementedBeaconIamServiceServer) Check(ctx context.Context, req *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedBeaconIamServiceServer) Watch(req *HealthCheckRequest, srv BeaconIamService_WatchServer) error {
	return status.Errorf(codes.Unimplemented, "method Watch not implemented")
}
func (*UnimplementedBeaconIamServiceServer) AuthLogin(ctx context.Context, req *AuthLoginRequest) (*AuthLoginResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthLogin not implemented")
}
func (*UnimplementedBeaconIamServiceServer) AuthLogout(ctx context.Context, req *AuthLogoutRequest) (*AuthLogoutResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthLogout not implemented")
}
func (*UnimplementedBeaconIamServiceServer) AuthResetPassword(ctx context.Context, req *AuthResetPasswordRequest) (*AuthResetPasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthResetPassword not implemented")
}
func (*UnimplementedBeaconIamServiceServer) RequestAuthorisation(ctx context.Context, req *AuthorisationRequest) (*AuthorisationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestAuthorisation not implemented")
}
func (*UnimplementedBeaconIamServiceServer) AdminUserCreate(ctx context.Context, req *AdminUserCreateRequest) (*AdminUserCreateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUserCreate not implemented")
}
func (*UnimplementedBeaconIamServiceServer) AdminUserFind(ctx context.Context, req *AdminUserFindRequest) (*AdminUserFindResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUserFind not implemented")
}
func (*UnimplementedBeaconIamServiceServer) AdminUserFindOne(ctx context.Context, req *AdminUserFindOneRequest) (*AdminUserFindOneResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUserFindOne not implemented")
}
func (*UnimplementedBeaconIamServiceServer) AdminUserFindByID(ctx context.Context, req *AdminUserFindByIdRequest) (*AdminUserFindByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUserFindByID not implemented")
}
func (*UnimplementedBeaconIamServiceServer) AdminUserCount(ctx context.Context, req *AdminUserCountRequest) (*AdminUserCountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUserCount not implemented")
}
func (*UnimplementedBeaconIamServiceServer) AdminUserUpdate(ctx context.Context, req *AdminUserUpdateRequest) (*AdminUserUpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUserUpdate not implemented")
}
func (*UnimplementedBeaconIamServiceServer) AdminUserDeleteByID(ctx context.Context, req *AdminUserDeleteByIdRequest) (*AdminUserDeleteByIdResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUserDeleteByID not implemented")
}
func (*UnimplementedBeaconIamServiceServer) AdminUserDeleteWithWhere(ctx context.Context, req *AdminUserDeleteWithWhereRequest) (*AdminUserDeleteWithWhereResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AdminUserDeleteWithWhere not implemented")
}

func RegisterBeaconIamServiceServer(s *grpc.Server, srv BeaconIamServiceServer) {
	s.RegisterService(&_BeaconIamService_serviceDesc, srv)
}

func _BeaconIamService_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconIamServiceServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconIamService/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconIamServiceServer).Check(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconIamService_Watch_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(HealthCheckRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BeaconIamServiceServer).Watch(m, &beaconIamServiceWatchServer{stream})
}

type BeaconIamService_WatchServer interface {
	Send(*HealthCheckResponse) error
	grpc.ServerStream
}

type beaconIamServiceWatchServer struct {
	grpc.ServerStream
}

func (x *beaconIamServiceWatchServer) Send(m *HealthCheckResponse) error {
	return x.ServerStream.SendMsg(m)
}

func _BeaconIamService_AuthLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthLoginRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconIamServiceServer).AuthLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconIamService/AuthLogin",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconIamServiceServer).AuthLogin(ctx, req.(*AuthLoginRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconIamService_AuthLogout_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthLogoutRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconIamServiceServer).AuthLogout(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconIamService/AuthLogout",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconIamServiceServer).AuthLogout(ctx, req.(*AuthLogoutRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconIamService_AuthResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthResetPasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconIamServiceServer).AuthResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconIamService/AuthResetPassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconIamServiceServer).AuthResetPassword(ctx, req.(*AuthResetPasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconIamService_RequestAuthorisation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorisationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconIamServiceServer).RequestAuthorisation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconIamService/RequestAuthorisation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconIamServiceServer).RequestAuthorisation(ctx, req.(*AuthorisationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconIamService_AdminUserCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUserCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconIamServiceServer).AdminUserCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconIamService/AdminUserCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconIamServiceServer).AdminUserCreate(ctx, req.(*AdminUserCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconIamService_AdminUserFind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUserFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconIamServiceServer).AdminUserFind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconIamService/AdminUserFind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconIamServiceServer).AdminUserFind(ctx, req.(*AdminUserFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconIamService_AdminUserFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUserFindOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconIamServiceServer).AdminUserFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconIamService/AdminUserFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconIamServiceServer).AdminUserFindOne(ctx, req.(*AdminUserFindOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconIamService_AdminUserFindByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUserFindByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconIamServiceServer).AdminUserFindByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconIamService/AdminUserFindByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconIamServiceServer).AdminUserFindByID(ctx, req.(*AdminUserFindByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconIamService_AdminUserCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUserCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconIamServiceServer).AdminUserCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconIamService/AdminUserCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconIamServiceServer).AdminUserCount(ctx, req.(*AdminUserCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconIamService_AdminUserUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUserUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconIamServiceServer).AdminUserUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconIamService/AdminUserUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconIamServiceServer).AdminUserUpdate(ctx, req.(*AdminUserUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconIamService_AdminUserDeleteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUserDeleteByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconIamServiceServer).AdminUserDeleteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconIamService/AdminUserDeleteByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconIamServiceServer).AdminUserDeleteByID(ctx, req.(*AdminUserDeleteByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconIamService_AdminUserDeleteWithWhere_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AdminUserDeleteWithWhereRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconIamServiceServer).AdminUserDeleteWithWhere(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconIamService/AdminUserDeleteWithWhere",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconIamServiceServer).AdminUserDeleteWithWhere(ctx, req.(*AdminUserDeleteWithWhereRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BeaconIamService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbx.BeaconIamService",
	HandlerType: (*BeaconIamServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _BeaconIamService_Check_Handler,
		},
		{
			MethodName: "AuthLogin",
			Handler:    _BeaconIamService_AuthLogin_Handler,
		},
		{
			MethodName: "AuthLogout",
			Handler:    _BeaconIamService_AuthLogout_Handler,
		},
		{
			MethodName: "AuthResetPassword",
			Handler:    _BeaconIamService_AuthResetPassword_Handler,
		},
		{
			MethodName: "RequestAuthorisation",
			Handler:    _BeaconIamService_RequestAuthorisation_Handler,
		},
		{
			MethodName: "AdminUserCreate",
			Handler:    _BeaconIamService_AdminUserCreate_Handler,
		},
		{
			MethodName: "AdminUserFind",
			Handler:    _BeaconIamService_AdminUserFind_Handler,
		},
		{
			MethodName: "AdminUserFindOne",
			Handler:    _BeaconIamService_AdminUserFindOne_Handler,
		},
		{
			MethodName: "AdminUserFindByID",
			Handler:    _BeaconIamService_AdminUserFindByID_Handler,
		},
		{
			MethodName: "AdminUserCount",
			Handler:    _BeaconIamService_AdminUserCount_Handler,
		},
		{
			MethodName: "AdminUserUpdate",
			Handler:    _BeaconIamService_AdminUserUpdate_Handler,
		},
		{
			MethodName: "AdminUserDeleteByID",
			Handler:    _BeaconIamService_AdminUserDeleteByID_Handler,
		},
		{
			MethodName: "AdminUserDeleteWithWhere",
			Handler:    _BeaconIamService_AdminUserDeleteWithWhere_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Watch",
			Handler:       _BeaconIamService_Watch_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "pbx/iam.proto",
}
