// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbx/srm.proto

package pbx

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ----------------------------------------
// Course Model
// ----------------------------------------
type Course struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Credits              float32  `protobuf:"fixed32,5,opt,name=credits,proto3" json:"credits,omitempty"`
	Owner                int32    `protobuf:"varint,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Type                 string   `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	PreCourse            string   `protobuf:"bytes,8,opt,name=pre_course,json=preCourse,proto3" json:"pre_course,omitempty"`
	SchemeId             string   `protobuf:"bytes,9,opt,name=schemeId,proto3" json:"schemeId,omitempty"`
	Status               bool     `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	Scheme               *Scheme  `protobuf:"bytes,11,opt,name=scheme,proto3" json:"scheme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Course) Reset()         { *m = Course{} }
func (m *Course) String() string { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()    {}
func (*Course) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{0}
}

func (m *Course) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Course.Unmarshal(m, b)
}
func (m *Course) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Course.Marshal(b, m, deterministic)
}
func (m *Course) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Course.Merge(m, src)
}
func (m *Course) XXX_Size() int {
	return xxx_messageInfo_Course.Size(m)
}
func (m *Course) XXX_DiscardUnknown() {
	xxx_messageInfo_Course.DiscardUnknown(m)
}

var xxx_messageInfo_Course proto.InternalMessageInfo

func (m *Course) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Course) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Course) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Course) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Course) GetCredits() float32 {
	if m != nil {
		return m.Credits
	}
	return 0
}

func (m *Course) GetOwner() int32 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *Course) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Course) GetPreCourse() string {
	if m != nil {
		return m.PreCourse
	}
	return ""
}

func (m *Course) GetSchemeId() string {
	if m != nil {
		return m.SchemeId
	}
	return ""
}

func (m *Course) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Course) GetScheme() *Scheme {
	if m != nil {
		return m.Scheme
	}
	return nil
}

type CourseCreateRequest struct {
	Course               *Course  `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseCreateRequest) Reset()         { *m = CourseCreateRequest{} }
func (m *CourseCreateRequest) String() string { return proto.CompactTextString(m) }
func (*CourseCreateRequest) ProtoMessage()    {}
func (*CourseCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{1}
}

func (m *CourseCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseCreateRequest.Unmarshal(m, b)
}
func (m *CourseCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseCreateRequest.Marshal(b, m, deterministic)
}
func (m *CourseCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseCreateRequest.Merge(m, src)
}
func (m *CourseCreateRequest) XXX_Size() int {
	return xxx_messageInfo_CourseCreateRequest.Size(m)
}
func (m *CourseCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CourseCreateRequest proto.InternalMessageInfo

func (m *CourseCreateRequest) GetCourse() *Course {
	if m != nil {
		return m.Course
	}
	return nil
}

type CourseCreateResponse struct {
	Course               *Course  `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseCreateResponse) Reset()         { *m = CourseCreateResponse{} }
func (m *CourseCreateResponse) String() string { return proto.CompactTextString(m) }
func (*CourseCreateResponse) ProtoMessage()    {}
func (*CourseCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{2}
}

func (m *CourseCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseCreateResponse.Unmarshal(m, b)
}
func (m *CourseCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseCreateResponse.Marshal(b, m, deterministic)
}
func (m *CourseCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseCreateResponse.Merge(m, src)
}
func (m *CourseCreateResponse) XXX_Size() int {
	return xxx_messageInfo_CourseCreateResponse.Size(m)
}
func (m *CourseCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CourseCreateResponse proto.InternalMessageInfo

func (m *CourseCreateResponse) GetCourse() *Course {
	if m != nil {
		return m.Course
	}
	return nil
}

type CourseFindRequest struct {
	Filter               string   `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseFindRequest) Reset()         { *m = CourseFindRequest{} }
func (m *CourseFindRequest) String() string { return proto.CompactTextString(m) }
func (*CourseFindRequest) ProtoMessage()    {}
func (*CourseFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{3}
}

func (m *CourseFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseFindRequest.Unmarshal(m, b)
}
func (m *CourseFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseFindRequest.Marshal(b, m, deterministic)
}
func (m *CourseFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseFindRequest.Merge(m, src)
}
func (m *CourseFindRequest) XXX_Size() int {
	return xxx_messageInfo_CourseFindRequest.Size(m)
}
func (m *CourseFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CourseFindRequest proto.InternalMessageInfo

func (m *CourseFindRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

type CourseFindResponse struct {
	Courses              []*Course `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CourseFindResponse) Reset()         { *m = CourseFindResponse{} }
func (m *CourseFindResponse) String() string { return proto.CompactTextString(m) }
func (*CourseFindResponse) ProtoMessage()    {}
func (*CourseFindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{4}
}

func (m *CourseFindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseFindResponse.Unmarshal(m, b)
}
func (m *CourseFindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseFindResponse.Marshal(b, m, deterministic)
}
func (m *CourseFindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseFindResponse.Merge(m, src)
}
func (m *CourseFindResponse) XXX_Size() int {
	return xxx_messageInfo_CourseFindResponse.Size(m)
}
func (m *CourseFindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseFindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CourseFindResponse proto.InternalMessageInfo

func (m *CourseFindResponse) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

//
// ----------------------------------------
// Scheme Model
// ----------------------------------------
type Scheme struct {
	Id                   string    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Scheme               string    `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Status               bool      `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	Courses              []*Course `protobuf:"bytes,4,rep,name=courses,proto3" json:"courses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *Scheme) Reset()         { *m = Scheme{} }
func (m *Scheme) String() string { return proto.CompactTextString(m) }
func (*Scheme) ProtoMessage()    {}
func (*Scheme) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{5}
}

func (m *Scheme) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scheme.Unmarshal(m, b)
}
func (m *Scheme) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scheme.Marshal(b, m, deterministic)
}
func (m *Scheme) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scheme.Merge(m, src)
}
func (m *Scheme) XXX_Size() int {
	return xxx_messageInfo_Scheme.Size(m)
}
func (m *Scheme) XXX_DiscardUnknown() {
	xxx_messageInfo_Scheme.DiscardUnknown(m)
}

var xxx_messageInfo_Scheme proto.InternalMessageInfo

func (m *Scheme) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Scheme) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *Scheme) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Scheme) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

type SchemeCreateRequest struct {
	Scheme               *Scheme  `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemeCreateRequest) Reset()         { *m = SchemeCreateRequest{} }
func (m *SchemeCreateRequest) String() string { return proto.CompactTextString(m) }
func (*SchemeCreateRequest) ProtoMessage()    {}
func (*SchemeCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{6}
}

func (m *SchemeCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeCreateRequest.Unmarshal(m, b)
}
func (m *SchemeCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeCreateRequest.Marshal(b, m, deterministic)
}
func (m *SchemeCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeCreateRequest.Merge(m, src)
}
func (m *SchemeCreateRequest) XXX_Size() int {
	return xxx_messageInfo_SchemeCreateRequest.Size(m)
}
func (m *SchemeCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeCreateRequest proto.InternalMessageInfo

func (m *SchemeCreateRequest) GetScheme() *Scheme {
	if m != nil {
		return m.Scheme
	}
	return nil
}

type SchemeCreateResponse struct {
	Scheme               *Scheme  `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemeCreateResponse) Reset()         { *m = SchemeCreateResponse{} }
func (m *SchemeCreateResponse) String() string { return proto.CompactTextString(m) }
func (*SchemeCreateResponse) ProtoMessage()    {}
func (*SchemeCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{7}
}

func (m *SchemeCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeCreateResponse.Unmarshal(m, b)
}
func (m *SchemeCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeCreateResponse.Marshal(b, m, deterministic)
}
func (m *SchemeCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeCreateResponse.Merge(m, src)
}
func (m *SchemeCreateResponse) XXX_Size() int {
	return xxx_messageInfo_SchemeCreateResponse.Size(m)
}
func (m *SchemeCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeCreateResponse proto.InternalMessageInfo

func (m *SchemeCreateResponse) GetScheme() *Scheme {
	if m != nil {
		return m.Scheme
	}
	return nil
}

func init() {
	proto.RegisterType((*Course)(nil), "pbx.Course")
	proto.RegisterType((*CourseCreateRequest)(nil), "pbx.CourseCreateRequest")
	proto.RegisterType((*CourseCreateResponse)(nil), "pbx.CourseCreateResponse")
	proto.RegisterType((*CourseFindRequest)(nil), "pbx.CourseFindRequest")
	proto.RegisterType((*CourseFindResponse)(nil), "pbx.CourseFindResponse")
	proto.RegisterType((*Scheme)(nil), "pbx.Scheme")
	proto.RegisterType((*SchemeCreateRequest)(nil), "pbx.SchemeCreateRequest")
	proto.RegisterType((*SchemeCreateResponse)(nil), "pbx.SchemeCreateResponse")
}

func init() { proto.RegisterFile("pbx/srm.proto", fileDescriptor_694536902d7906af) }

var fileDescriptor_694536902d7906af = []byte{
	// 432 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x53, 0x61, 0xab, 0xd3, 0x30,
	0x14, 0x25, 0xdd, 0xd6, 0x6d, 0xb7, 0x4f, 0xd1, 0xbc, 0x51, 0xe3, 0x40, 0x28, 0x15, 0xa1, 0x20,
	0x4c, 0x78, 0x7e, 0x7b, 0xc3, 0x2f, 0x16, 0x04, 0xbf, 0x76, 0x3f, 0x40, 0xd6, 0xf6, 0x8a, 0x81,
	0xb7, 0x26, 0x26, 0x99, 0xce, 0x7f, 0xe3, 0xff, 0xf2, 0xcf, 0x48, 0x93, 0xec, 0x2d, 0x75, 0x53,
	0xdf, 0xb7, 0xde, 0x7b, 0xee, 0xc9, 0x39, 0x39, 0x37, 0x85, 0x47, 0xb2, 0x3e, 0xbc, 0xd1, 0x6a,
	0xb7, 0x92, 0x4a, 0x18, 0x41, 0x47, 0xb2, 0x3e, 0xe4, 0x3f, 0x23, 0x88, 0x4b, 0xb1, 0x57, 0x1a,
	0xe9, 0x63, 0x88, 0x78, 0xcb, 0x48, 0x46, 0x8a, 0x79, 0x15, 0xf1, 0x96, 0x52, 0x18, 0x37, 0xa2,
	0x45, 0x16, 0xd9, 0x8e, 0xfd, 0xa6, 0x0b, 0x98, 0x18, 0x6e, 0xee, 0x90, 0x8d, 0x6c, 0xd3, 0x15,
	0x34, 0x83, 0xa4, 0x45, 0xdd, 0x28, 0x2e, 0x0d, 0x17, 0x1d, 0x1b, 0x5b, 0x2c, 0x6c, 0x51, 0x06,
	0xd3, 0x46, 0x61, 0xcb, 0x8d, 0x66, 0x93, 0x8c, 0x14, 0x51, 0x75, 0x2c, 0xfb, 0x13, 0xc5, 0xf7,
	0x0e, 0x15, 0x8b, 0x33, 0x52, 0x4c, 0x2a, 0x57, 0xf4, 0xda, 0xe6, 0x87, 0x44, 0x36, 0x75, 0xda,
	0xfd, 0x37, 0x7d, 0x01, 0x20, 0x15, 0x7e, 0x6a, 0xac, 0x5b, 0x36, 0xb3, 0xc8, 0x5c, 0x2a, 0xf4,
	0xf6, 0x97, 0x30, 0xd3, 0xcd, 0x17, 0xdc, 0xe1, 0xc7, 0x96, 0xcd, 0x2d, 0x78, 0x5f, 0xd3, 0x14,
	0x62, 0x6d, 0xb6, 0x66, 0xaf, 0x19, 0x64, 0xa4, 0x98, 0x55, 0xbe, 0xa2, 0x2f, 0x21, 0x76, 0x33,
	0x2c, 0xc9, 0x48, 0x91, 0xdc, 0x24, 0x2b, 0x59, 0x1f, 0x56, 0x1b, 0xdb, 0xaa, 0x3c, 0x94, 0xdf,
	0xc2, 0xb5, 0x93, 0x28, 0x15, 0x6e, 0x0d, 0x56, 0xf8, 0x75, 0x8f, 0xda, 0xf4, 0x5c, 0x6f, 0x85,
	0x04, 0x5c, 0x37, 0x59, 0x79, 0x28, 0x5f, 0xc3, 0x62, 0xc8, 0xd5, 0x52, 0x74, 0x1a, 0x1f, 0x46,
	0x7e, 0x0d, 0x4f, 0x5d, 0xe7, 0x03, 0xef, 0xda, 0xa3, 0x6c, 0x0a, 0xf1, 0x67, 0x7e, 0x67, 0x50,
	0xf9, 0x4d, 0xf9, 0x2a, 0x5f, 0x03, 0x0d, 0x87, 0xbd, 0xce, 0x2b, 0x98, 0xba, 0xc3, 0x34, 0x23,
	0xd9, 0xe8, 0x4f, 0xa1, 0x23, 0x96, 0x0b, 0x88, 0xdd, 0xa5, 0xcf, 0x1e, 0x41, 0x7a, 0x9f, 0x90,
	0x7b, 0x06, 0xbe, 0x0a, 0x12, 0x1d, 0x0d, 0x12, 0x0d, 0x04, 0xc7, 0xff, 0x10, 0xbc, 0x85, 0x6b,
	0x27, 0x78, 0x96, 0xa9, 0x57, 0x23, 0x7f, 0xdf, 0xc7, 0x1a, 0x16, 0x43, 0xee, 0x29, 0xd3, 0xff,
	0x92, 0x6f, 0x7e, 0x11, 0x78, 0xf2, 0x1e, 0xb7, 0x8d, 0xe8, 0x36, 0x6a, 0xb7, 0x41, 0xf5, 0x8d,
	0x37, 0x48, 0x4b, 0xb8, 0x0a, 0xb7, 0x44, 0x59, 0xe0, 0x79, 0x60, 0x70, 0xf9, 0xfc, 0x02, 0xe2,
	0xe5, 0xdf, 0x01, 0x9c, 0x16, 0x40, 0xd3, 0x60, 0x30, 0x58, 0xdf, 0xf2, 0xd9, 0x59, 0xdf, 0xd3,
	0x4b, 0xb8, 0x0a, 0x6f, 0xe5, 0x3d, 0x5c, 0x08, 0xc9, 0x7b, 0xb8, 0x14, 0x41, 0x1d, 0xdb, 0x3f,
	0xfb, 0xed, 0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x3b, 0x84, 0x74, 0x79, 0xea, 0x03, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BeaconSrmServiceClient is the client API for BeaconSrmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BeaconSrmServiceClient interface {
	// Course
	CourseCreate(ctx context.Context, in *CourseCreateRequest, opts ...grpc.CallOption) (*CourseCreateResponse, error)
	CourseFind(ctx context.Context, in *CourseFindRequest, opts ...grpc.CallOption) (*CourseFindResponse, error)
	// Scheme
	SchemeCreate(ctx context.Context, in *SchemeCreateRequest, opts ...grpc.CallOption) (*SchemeCreateResponse, error)
}

type beaconSrmServiceClient struct {
	cc *grpc.ClientConn
}

func NewBeaconSrmServiceClient(cc *grpc.ClientConn) BeaconSrmServiceClient {
	return &beaconSrmServiceClient{cc}
}

func (c *beaconSrmServiceClient) CourseCreate(ctx context.Context, in *CourseCreateRequest, opts ...grpc.CallOption) (*CourseCreateResponse, error) {
	out := new(CourseCreateResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/CourseCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) CourseFind(ctx context.Context, in *CourseFindRequest, opts ...grpc.CallOption) (*CourseFindResponse, error) {
	out := new(CourseFindResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/CourseFind", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) SchemeCreate(ctx context.Context, in *SchemeCreateRequest, opts ...grpc.CallOption) (*SchemeCreateResponse, error) {
	out := new(SchemeCreateResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/SchemeCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeaconSrmServiceServer is the server API for BeaconSrmService service.
type BeaconSrmServiceServer interface {
	// Course
	CourseCreate(context.Context, *CourseCreateRequest) (*CourseCreateResponse, error)
	CourseFind(context.Context, *CourseFindRequest) (*CourseFindResponse, error)
	// Scheme
	SchemeCreate(context.Context, *SchemeCreateRequest) (*SchemeCreateResponse, error)
}

func RegisterBeaconSrmServiceServer(s *grpc.Server, srv BeaconSrmServiceServer) {
	s.RegisterService(&_BeaconSrmService_serviceDesc, srv)
}

func _BeaconSrmService_CourseCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).CourseCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/CourseCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).CourseCreate(ctx, req.(*CourseCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_CourseFind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).CourseFind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/CourseFind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).CourseFind(ctx, req.(*CourseFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_SchemeCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemeCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).SchemeCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/SchemeCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).SchemeCreate(ctx, req.(*SchemeCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BeaconSrmService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbx.BeaconSrmService",
	HandlerType: (*BeaconSrmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CourseCreate",
			Handler:    _BeaconSrmService_CourseCreate_Handler,
		},
		{
			MethodName: "CourseFind",
			Handler:    _BeaconSrmService_CourseFind_Handler,
		},
		{
			MethodName: "SchemeCreate",
			Handler:    _BeaconSrmService_SchemeCreate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbx/srm.proto",
}
