// Code generated by protoc-gen-go. DO NOT EDIT.
// source: pbx/srm.proto

package pbx

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// ----------------------------------------
// Course Model
// ----------------------------------------
type Course struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	Title                string   `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Description          string   `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Credits              float32  `protobuf:"fixed32,5,opt,name=credits,proto3" json:"credits,omitempty"`
	Owner                int32    `protobuf:"varint,6,opt,name=owner,proto3" json:"owner,omitempty"`
	Type                 string   `protobuf:"bytes,7,opt,name=type,proto3" json:"type,omitempty"`
	PreCourse            string   `protobuf:"bytes,8,opt,name=pre_course,json=preCourse,proto3" json:"pre_course,omitempty"`
	SchemeId             string   `protobuf:"bytes,9,opt,name=scheme_id,json=schemeId,proto3" json:"scheme_id,omitempty"`
	Status               bool     `protobuf:"varint,10,opt,name=status,proto3" json:"status,omitempty"`
	InstitutionId        string   `protobuf:"bytes,11,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	BXX_UpdatedFields    []string `protobuf:"bytes,12,rep,name=BXX__updated_fields,json=BXXUpdatedFields,proto3" json:"BXX__updated_fields,omitempty"`
	Scheme               *Scheme  `protobuf:"bytes,13,opt,name=scheme,proto3" json:"scheme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Course) Reset()         { *m = Course{} }
func (m *Course) String() string { return proto.CompactTextString(m) }
func (*Course) ProtoMessage()    {}
func (*Course) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{0}
}

func (m *Course) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Course.Unmarshal(m, b)
}
func (m *Course) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Course.Marshal(b, m, deterministic)
}
func (m *Course) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Course.Merge(m, src)
}
func (m *Course) XXX_Size() int {
	return xxx_messageInfo_Course.Size(m)
}
func (m *Course) XXX_DiscardUnknown() {
	xxx_messageInfo_Course.DiscardUnknown(m)
}

var xxx_messageInfo_Course proto.InternalMessageInfo

func (m *Course) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Course) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Course) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *Course) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func (m *Course) GetCredits() float32 {
	if m != nil {
		return m.Credits
	}
	return 0
}

func (m *Course) GetOwner() int32 {
	if m != nil {
		return m.Owner
	}
	return 0
}

func (m *Course) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Course) GetPreCourse() string {
	if m != nil {
		return m.PreCourse
	}
	return ""
}

func (m *Course) GetSchemeId() string {
	if m != nil {
		return m.SchemeId
	}
	return ""
}

func (m *Course) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Course) GetInstitutionId() string {
	if m != nil {
		return m.InstitutionId
	}
	return ""
}

func (m *Course) GetBXX_UpdatedFields() []string {
	if m != nil {
		return m.BXX_UpdatedFields
	}
	return nil
}

func (m *Course) GetScheme() *Scheme {
	if m != nil {
		return m.Scheme
	}
	return nil
}

type CourseFindRequest struct {
	Filter               string         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CourseFindRequest) Reset()         { *m = CourseFindRequest{} }
func (m *CourseFindRequest) String() string { return proto.CompactTextString(m) }
func (*CourseFindRequest) ProtoMessage()    {}
func (*CourseFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{1}
}

func (m *CourseFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseFindRequest.Unmarshal(m, b)
}
func (m *CourseFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseFindRequest.Marshal(b, m, deterministic)
}
func (m *CourseFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseFindRequest.Merge(m, src)
}
func (m *CourseFindRequest) XXX_Size() int {
	return xxx_messageInfo_CourseFindRequest.Size(m)
}
func (m *CourseFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CourseFindRequest proto.InternalMessageInfo

func (m *CourseFindRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *CourseFindRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type CourseFindResponse struct {
	Courses              []*Course `protobuf:"bytes,1,rep,name=courses,proto3" json:"courses,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *CourseFindResponse) Reset()         { *m = CourseFindResponse{} }
func (m *CourseFindResponse) String() string { return proto.CompactTextString(m) }
func (*CourseFindResponse) ProtoMessage()    {}
func (*CourseFindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{2}
}

func (m *CourseFindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseFindResponse.Unmarshal(m, b)
}
func (m *CourseFindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseFindResponse.Marshal(b, m, deterministic)
}
func (m *CourseFindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseFindResponse.Merge(m, src)
}
func (m *CourseFindResponse) XXX_Size() int {
	return xxx_messageInfo_CourseFindResponse.Size(m)
}
func (m *CourseFindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseFindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CourseFindResponse proto.InternalMessageInfo

func (m *CourseFindResponse) GetCourses() []*Course {
	if m != nil {
		return m.Courses
	}
	return nil
}

type CourseFindOneRequest struct {
	Filter               string         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CourseFindOneRequest) Reset()         { *m = CourseFindOneRequest{} }
func (m *CourseFindOneRequest) String() string { return proto.CompactTextString(m) }
func (*CourseFindOneRequest) ProtoMessage()    {}
func (*CourseFindOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{3}
}

func (m *CourseFindOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseFindOneRequest.Unmarshal(m, b)
}
func (m *CourseFindOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseFindOneRequest.Marshal(b, m, deterministic)
}
func (m *CourseFindOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseFindOneRequest.Merge(m, src)
}
func (m *CourseFindOneRequest) XXX_Size() int {
	return xxx_messageInfo_CourseFindOneRequest.Size(m)
}
func (m *CourseFindOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseFindOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CourseFindOneRequest proto.InternalMessageInfo

func (m *CourseFindOneRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *CourseFindOneRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type CourseFindOneResponse struct {
	Course               *Course  `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseFindOneResponse) Reset()         { *m = CourseFindOneResponse{} }
func (m *CourseFindOneResponse) String() string { return proto.CompactTextString(m) }
func (*CourseFindOneResponse) ProtoMessage()    {}
func (*CourseFindOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{4}
}

func (m *CourseFindOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseFindOneResponse.Unmarshal(m, b)
}
func (m *CourseFindOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseFindOneResponse.Marshal(b, m, deterministic)
}
func (m *CourseFindOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseFindOneResponse.Merge(m, src)
}
func (m *CourseFindOneResponse) XXX_Size() int {
	return xxx_messageInfo_CourseFindOneResponse.Size(m)
}
func (m *CourseFindOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseFindOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CourseFindOneResponse proto.InternalMessageInfo

func (m *CourseFindOneResponse) GetCourse() *Course {
	if m != nil {
		return m.Course
	}
	return nil
}

type CourseCreateRequest struct {
	Course               *Course        `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CourseCreateRequest) Reset()         { *m = CourseCreateRequest{} }
func (m *CourseCreateRequest) String() string { return proto.CompactTextString(m) }
func (*CourseCreateRequest) ProtoMessage()    {}
func (*CourseCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{5}
}

func (m *CourseCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseCreateRequest.Unmarshal(m, b)
}
func (m *CourseCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseCreateRequest.Marshal(b, m, deterministic)
}
func (m *CourseCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseCreateRequest.Merge(m, src)
}
func (m *CourseCreateRequest) XXX_Size() int {
	return xxx_messageInfo_CourseCreateRequest.Size(m)
}
func (m *CourseCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CourseCreateRequest proto.InternalMessageInfo

func (m *CourseCreateRequest) GetCourse() *Course {
	if m != nil {
		return m.Course
	}
	return nil
}

func (m *CourseCreateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type CourseCreateResponse struct {
	Course               *Course  `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseCreateResponse) Reset()         { *m = CourseCreateResponse{} }
func (m *CourseCreateResponse) String() string { return proto.CompactTextString(m) }
func (*CourseCreateResponse) ProtoMessage()    {}
func (*CourseCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{6}
}

func (m *CourseCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseCreateResponse.Unmarshal(m, b)
}
func (m *CourseCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseCreateResponse.Marshal(b, m, deterministic)
}
func (m *CourseCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseCreateResponse.Merge(m, src)
}
func (m *CourseCreateResponse) XXX_Size() int {
	return xxx_messageInfo_CourseCreateResponse.Size(m)
}
func (m *CourseCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CourseCreateResponse proto.InternalMessageInfo

func (m *CourseCreateResponse) GetCourse() *Course {
	if m != nil {
		return m.Course
	}
	return nil
}

type CourseFindByIdRequest struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filter               string         `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CourseFindByIdRequest) Reset()         { *m = CourseFindByIdRequest{} }
func (m *CourseFindByIdRequest) String() string { return proto.CompactTextString(m) }
func (*CourseFindByIdRequest) ProtoMessage()    {}
func (*CourseFindByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{7}
}

func (m *CourseFindByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseFindByIdRequest.Unmarshal(m, b)
}
func (m *CourseFindByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseFindByIdRequest.Marshal(b, m, deterministic)
}
func (m *CourseFindByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseFindByIdRequest.Merge(m, src)
}
func (m *CourseFindByIdRequest) XXX_Size() int {
	return xxx_messageInfo_CourseFindByIdRequest.Size(m)
}
func (m *CourseFindByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseFindByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CourseFindByIdRequest proto.InternalMessageInfo

func (m *CourseFindByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CourseFindByIdRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *CourseFindByIdRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type CourseFindByIdResponse struct {
	Course               *Course  `protobuf:"bytes,1,opt,name=course,proto3" json:"course,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseFindByIdResponse) Reset()         { *m = CourseFindByIdResponse{} }
func (m *CourseFindByIdResponse) String() string { return proto.CompactTextString(m) }
func (*CourseFindByIdResponse) ProtoMessage()    {}
func (*CourseFindByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{8}
}

func (m *CourseFindByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseFindByIdResponse.Unmarshal(m, b)
}
func (m *CourseFindByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseFindByIdResponse.Marshal(b, m, deterministic)
}
func (m *CourseFindByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseFindByIdResponse.Merge(m, src)
}
func (m *CourseFindByIdResponse) XXX_Size() int {
	return xxx_messageInfo_CourseFindByIdResponse.Size(m)
}
func (m *CourseFindByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseFindByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CourseFindByIdResponse proto.InternalMessageInfo

func (m *CourseFindByIdResponse) GetCourse() *Course {
	if m != nil {
		return m.Course
	}
	return nil
}

type CourseCountRequest struct {
	Filter               string         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CourseCountRequest) Reset()         { *m = CourseCountRequest{} }
func (m *CourseCountRequest) String() string { return proto.CompactTextString(m) }
func (*CourseCountRequest) ProtoMessage()    {}
func (*CourseCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{9}
}

func (m *CourseCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseCountRequest.Unmarshal(m, b)
}
func (m *CourseCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseCountRequest.Marshal(b, m, deterministic)
}
func (m *CourseCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseCountRequest.Merge(m, src)
}
func (m *CourseCountRequest) XXX_Size() int {
	return xxx_messageInfo_CourseCountRequest.Size(m)
}
func (m *CourseCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CourseCountRequest proto.InternalMessageInfo

func (m *CourseCountRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *CourseCountRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type CourseCountResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseCountResponse) Reset()         { *m = CourseCountResponse{} }
func (m *CourseCountResponse) String() string { return proto.CompactTextString(m) }
func (*CourseCountResponse) ProtoMessage()    {}
func (*CourseCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{10}
}

func (m *CourseCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseCountResponse.Unmarshal(m, b)
}
func (m *CourseCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseCountResponse.Marshal(b, m, deterministic)
}
func (m *CourseCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseCountResponse.Merge(m, src)
}
func (m *CourseCountResponse) XXX_Size() int {
	return xxx_messageInfo_CourseCountResponse.Size(m)
}
func (m *CourseCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CourseCountResponse proto.InternalMessageInfo

func (m *CourseCountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type CourseUpdateRequest struct {
	Where                string         `protobuf:"bytes,1,opt,name=where,proto3" json:"where,omitempty"`
	Course               *Course        `protobuf:"bytes,2,opt,name=course,proto3" json:"course,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CourseUpdateRequest) Reset()         { *m = CourseUpdateRequest{} }
func (m *CourseUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*CourseUpdateRequest) ProtoMessage()    {}
func (*CourseUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{11}
}

func (m *CourseUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseUpdateRequest.Unmarshal(m, b)
}
func (m *CourseUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseUpdateRequest.Marshal(b, m, deterministic)
}
func (m *CourseUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseUpdateRequest.Merge(m, src)
}
func (m *CourseUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_CourseUpdateRequest.Size(m)
}
func (m *CourseUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CourseUpdateRequest proto.InternalMessageInfo

func (m *CourseUpdateRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

func (m *CourseUpdateRequest) GetCourse() *Course {
	if m != nil {
		return m.Course
	}
	return nil
}

func (m *CourseUpdateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type CourseUpdateResponse struct {
	Updated              bool     `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseUpdateResponse) Reset()         { *m = CourseUpdateResponse{} }
func (m *CourseUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*CourseUpdateResponse) ProtoMessage()    {}
func (*CourseUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{12}
}

func (m *CourseUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseUpdateResponse.Unmarshal(m, b)
}
func (m *CourseUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseUpdateResponse.Marshal(b, m, deterministic)
}
func (m *CourseUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseUpdateResponse.Merge(m, src)
}
func (m *CourseUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_CourseUpdateResponse.Size(m)
}
func (m *CourseUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CourseUpdateResponse proto.InternalMessageInfo

func (m *CourseUpdateResponse) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

type CourseDeleteByIdRequest struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CourseDeleteByIdRequest) Reset()         { *m = CourseDeleteByIdRequest{} }
func (m *CourseDeleteByIdRequest) String() string { return proto.CompactTextString(m) }
func (*CourseDeleteByIdRequest) ProtoMessage()    {}
func (*CourseDeleteByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{13}
}

func (m *CourseDeleteByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseDeleteByIdRequest.Unmarshal(m, b)
}
func (m *CourseDeleteByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseDeleteByIdRequest.Marshal(b, m, deterministic)
}
func (m *CourseDeleteByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseDeleteByIdRequest.Merge(m, src)
}
func (m *CourseDeleteByIdRequest) XXX_Size() int {
	return xxx_messageInfo_CourseDeleteByIdRequest.Size(m)
}
func (m *CourseDeleteByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseDeleteByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CourseDeleteByIdRequest proto.InternalMessageInfo

func (m *CourseDeleteByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *CourseDeleteByIdRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type CourseDeleteByIdResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseDeleteByIdResponse) Reset()         { *m = CourseDeleteByIdResponse{} }
func (m *CourseDeleteByIdResponse) String() string { return proto.CompactTextString(m) }
func (*CourseDeleteByIdResponse) ProtoMessage()    {}
func (*CourseDeleteByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{14}
}

func (m *CourseDeleteByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseDeleteByIdResponse.Unmarshal(m, b)
}
func (m *CourseDeleteByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseDeleteByIdResponse.Marshal(b, m, deterministic)
}
func (m *CourseDeleteByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseDeleteByIdResponse.Merge(m, src)
}
func (m *CourseDeleteByIdResponse) XXX_Size() int {
	return xxx_messageInfo_CourseDeleteByIdResponse.Size(m)
}
func (m *CourseDeleteByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseDeleteByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CourseDeleteByIdResponse proto.InternalMessageInfo

func (m *CourseDeleteByIdResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type CourseDeleteWithWhereRequest struct {
	Where                string         `protobuf:"bytes,1,opt,name=where,proto3" json:"where,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *CourseDeleteWithWhereRequest) Reset()         { *m = CourseDeleteWithWhereRequest{} }
func (m *CourseDeleteWithWhereRequest) String() string { return proto.CompactTextString(m) }
func (*CourseDeleteWithWhereRequest) ProtoMessage()    {}
func (*CourseDeleteWithWhereRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{15}
}

func (m *CourseDeleteWithWhereRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseDeleteWithWhereRequest.Unmarshal(m, b)
}
func (m *CourseDeleteWithWhereRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseDeleteWithWhereRequest.Marshal(b, m, deterministic)
}
func (m *CourseDeleteWithWhereRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseDeleteWithWhereRequest.Merge(m, src)
}
func (m *CourseDeleteWithWhereRequest) XXX_Size() int {
	return xxx_messageInfo_CourseDeleteWithWhereRequest.Size(m)
}
func (m *CourseDeleteWithWhereRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseDeleteWithWhereRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CourseDeleteWithWhereRequest proto.InternalMessageInfo

func (m *CourseDeleteWithWhereRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

func (m *CourseDeleteWithWhereRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type CourseDeleteWithWhereResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CourseDeleteWithWhereResponse) Reset()         { *m = CourseDeleteWithWhereResponse{} }
func (m *CourseDeleteWithWhereResponse) String() string { return proto.CompactTextString(m) }
func (*CourseDeleteWithWhereResponse) ProtoMessage()    {}
func (*CourseDeleteWithWhereResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{16}
}

func (m *CourseDeleteWithWhereResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CourseDeleteWithWhereResponse.Unmarshal(m, b)
}
func (m *CourseDeleteWithWhereResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CourseDeleteWithWhereResponse.Marshal(b, m, deterministic)
}
func (m *CourseDeleteWithWhereResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CourseDeleteWithWhereResponse.Merge(m, src)
}
func (m *CourseDeleteWithWhereResponse) XXX_Size() int {
	return xxx_messageInfo_CourseDeleteWithWhereResponse.Size(m)
}
func (m *CourseDeleteWithWhereResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CourseDeleteWithWhereResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CourseDeleteWithWhereResponse proto.InternalMessageInfo

func (m *CourseDeleteWithWhereResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

//
// ----------------------------------------
// Scheme Model
// ----------------------------------------
type Scheme struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Scheme               string   `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Status               bool     `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	InstitutionId        string   `protobuf:"bytes,4,opt,name=institution_id,json=institutionId,proto3" json:"institution_id,omitempty"`
	BXX_UpdatedFields    []string `protobuf:"bytes,5,rep,name=BXX__updated_fields,json=BXXUpdatedFields,proto3" json:"BXX__updated_fields,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Scheme) Reset()         { *m = Scheme{} }
func (m *Scheme) String() string { return proto.CompactTextString(m) }
func (*Scheme) ProtoMessage()    {}
func (*Scheme) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{17}
}

func (m *Scheme) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Scheme.Unmarshal(m, b)
}
func (m *Scheme) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Scheme.Marshal(b, m, deterministic)
}
func (m *Scheme) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Scheme.Merge(m, src)
}
func (m *Scheme) XXX_Size() int {
	return xxx_messageInfo_Scheme.Size(m)
}
func (m *Scheme) XXX_DiscardUnknown() {
	xxx_messageInfo_Scheme.DiscardUnknown(m)
}

var xxx_messageInfo_Scheme proto.InternalMessageInfo

func (m *Scheme) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Scheme) GetScheme() string {
	if m != nil {
		return m.Scheme
	}
	return ""
}

func (m *Scheme) GetStatus() bool {
	if m != nil {
		return m.Status
	}
	return false
}

func (m *Scheme) GetInstitutionId() string {
	if m != nil {
		return m.InstitutionId
	}
	return ""
}

func (m *Scheme) GetBXX_UpdatedFields() []string {
	if m != nil {
		return m.BXX_UpdatedFields
	}
	return nil
}

type SchemeFindRequest struct {
	Filter               string         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SchemeFindRequest) Reset()         { *m = SchemeFindRequest{} }
func (m *SchemeFindRequest) String() string { return proto.CompactTextString(m) }
func (*SchemeFindRequest) ProtoMessage()    {}
func (*SchemeFindRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{18}
}

func (m *SchemeFindRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeFindRequest.Unmarshal(m, b)
}
func (m *SchemeFindRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeFindRequest.Marshal(b, m, deterministic)
}
func (m *SchemeFindRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeFindRequest.Merge(m, src)
}
func (m *SchemeFindRequest) XXX_Size() int {
	return xxx_messageInfo_SchemeFindRequest.Size(m)
}
func (m *SchemeFindRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeFindRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeFindRequest proto.InternalMessageInfo

func (m *SchemeFindRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *SchemeFindRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type SchemeFindResponse struct {
	Schemes              []*Scheme `protobuf:"bytes,1,rep,name=schemes,proto3" json:"schemes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *SchemeFindResponse) Reset()         { *m = SchemeFindResponse{} }
func (m *SchemeFindResponse) String() string { return proto.CompactTextString(m) }
func (*SchemeFindResponse) ProtoMessage()    {}
func (*SchemeFindResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{19}
}

func (m *SchemeFindResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeFindResponse.Unmarshal(m, b)
}
func (m *SchemeFindResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeFindResponse.Marshal(b, m, deterministic)
}
func (m *SchemeFindResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeFindResponse.Merge(m, src)
}
func (m *SchemeFindResponse) XXX_Size() int {
	return xxx_messageInfo_SchemeFindResponse.Size(m)
}
func (m *SchemeFindResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeFindResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeFindResponse proto.InternalMessageInfo

func (m *SchemeFindResponse) GetSchemes() []*Scheme {
	if m != nil {
		return m.Schemes
	}
	return nil
}

type SchemeFindOneRequest struct {
	Filter               string         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SchemeFindOneRequest) Reset()         { *m = SchemeFindOneRequest{} }
func (m *SchemeFindOneRequest) String() string { return proto.CompactTextString(m) }
func (*SchemeFindOneRequest) ProtoMessage()    {}
func (*SchemeFindOneRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{20}
}

func (m *SchemeFindOneRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeFindOneRequest.Unmarshal(m, b)
}
func (m *SchemeFindOneRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeFindOneRequest.Marshal(b, m, deterministic)
}
func (m *SchemeFindOneRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeFindOneRequest.Merge(m, src)
}
func (m *SchemeFindOneRequest) XXX_Size() int {
	return xxx_messageInfo_SchemeFindOneRequest.Size(m)
}
func (m *SchemeFindOneRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeFindOneRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeFindOneRequest proto.InternalMessageInfo

func (m *SchemeFindOneRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *SchemeFindOneRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type SchemeFindOneResponse struct {
	Scheme               *Scheme  `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemeFindOneResponse) Reset()         { *m = SchemeFindOneResponse{} }
func (m *SchemeFindOneResponse) String() string { return proto.CompactTextString(m) }
func (*SchemeFindOneResponse) ProtoMessage()    {}
func (*SchemeFindOneResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{21}
}

func (m *SchemeFindOneResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeFindOneResponse.Unmarshal(m, b)
}
func (m *SchemeFindOneResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeFindOneResponse.Marshal(b, m, deterministic)
}
func (m *SchemeFindOneResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeFindOneResponse.Merge(m, src)
}
func (m *SchemeFindOneResponse) XXX_Size() int {
	return xxx_messageInfo_SchemeFindOneResponse.Size(m)
}
func (m *SchemeFindOneResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeFindOneResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeFindOneResponse proto.InternalMessageInfo

func (m *SchemeFindOneResponse) GetScheme() *Scheme {
	if m != nil {
		return m.Scheme
	}
	return nil
}

type SchemeCreateRequest struct {
	Scheme               *Scheme        `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SchemeCreateRequest) Reset()         { *m = SchemeCreateRequest{} }
func (m *SchemeCreateRequest) String() string { return proto.CompactTextString(m) }
func (*SchemeCreateRequest) ProtoMessage()    {}
func (*SchemeCreateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{22}
}

func (m *SchemeCreateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeCreateRequest.Unmarshal(m, b)
}
func (m *SchemeCreateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeCreateRequest.Marshal(b, m, deterministic)
}
func (m *SchemeCreateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeCreateRequest.Merge(m, src)
}
func (m *SchemeCreateRequest) XXX_Size() int {
	return xxx_messageInfo_SchemeCreateRequest.Size(m)
}
func (m *SchemeCreateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeCreateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeCreateRequest proto.InternalMessageInfo

func (m *SchemeCreateRequest) GetScheme() *Scheme {
	if m != nil {
		return m.Scheme
	}
	return nil
}

func (m *SchemeCreateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type SchemeCreateResponse struct {
	Scheme               *Scheme  `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemeCreateResponse) Reset()         { *m = SchemeCreateResponse{} }
func (m *SchemeCreateResponse) String() string { return proto.CompactTextString(m) }
func (*SchemeCreateResponse) ProtoMessage()    {}
func (*SchemeCreateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{23}
}

func (m *SchemeCreateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeCreateResponse.Unmarshal(m, b)
}
func (m *SchemeCreateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeCreateResponse.Marshal(b, m, deterministic)
}
func (m *SchemeCreateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeCreateResponse.Merge(m, src)
}
func (m *SchemeCreateResponse) XXX_Size() int {
	return xxx_messageInfo_SchemeCreateResponse.Size(m)
}
func (m *SchemeCreateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeCreateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeCreateResponse proto.InternalMessageInfo

func (m *SchemeCreateResponse) GetScheme() *Scheme {
	if m != nil {
		return m.Scheme
	}
	return nil
}

type SchemeFindByIdRequest struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Filter               string         `protobuf:"bytes,2,opt,name=filter,proto3" json:"filter,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SchemeFindByIdRequest) Reset()         { *m = SchemeFindByIdRequest{} }
func (m *SchemeFindByIdRequest) String() string { return proto.CompactTextString(m) }
func (*SchemeFindByIdRequest) ProtoMessage()    {}
func (*SchemeFindByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{24}
}

func (m *SchemeFindByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeFindByIdRequest.Unmarshal(m, b)
}
func (m *SchemeFindByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeFindByIdRequest.Marshal(b, m, deterministic)
}
func (m *SchemeFindByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeFindByIdRequest.Merge(m, src)
}
func (m *SchemeFindByIdRequest) XXX_Size() int {
	return xxx_messageInfo_SchemeFindByIdRequest.Size(m)
}
func (m *SchemeFindByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeFindByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeFindByIdRequest proto.InternalMessageInfo

func (m *SchemeFindByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SchemeFindByIdRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *SchemeFindByIdRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type SchemeFindByIdResponse struct {
	Scheme               *Scheme  `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemeFindByIdResponse) Reset()         { *m = SchemeFindByIdResponse{} }
func (m *SchemeFindByIdResponse) String() string { return proto.CompactTextString(m) }
func (*SchemeFindByIdResponse) ProtoMessage()    {}
func (*SchemeFindByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{25}
}

func (m *SchemeFindByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeFindByIdResponse.Unmarshal(m, b)
}
func (m *SchemeFindByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeFindByIdResponse.Marshal(b, m, deterministic)
}
func (m *SchemeFindByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeFindByIdResponse.Merge(m, src)
}
func (m *SchemeFindByIdResponse) XXX_Size() int {
	return xxx_messageInfo_SchemeFindByIdResponse.Size(m)
}
func (m *SchemeFindByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeFindByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeFindByIdResponse proto.InternalMessageInfo

func (m *SchemeFindByIdResponse) GetScheme() *Scheme {
	if m != nil {
		return m.Scheme
	}
	return nil
}

type SchemeCountRequest struct {
	Filter               string         `protobuf:"bytes,1,opt,name=filter,proto3" json:"filter,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SchemeCountRequest) Reset()         { *m = SchemeCountRequest{} }
func (m *SchemeCountRequest) String() string { return proto.CompactTextString(m) }
func (*SchemeCountRequest) ProtoMessage()    {}
func (*SchemeCountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{26}
}

func (m *SchemeCountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeCountRequest.Unmarshal(m, b)
}
func (m *SchemeCountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeCountRequest.Marshal(b, m, deterministic)
}
func (m *SchemeCountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeCountRequest.Merge(m, src)
}
func (m *SchemeCountRequest) XXX_Size() int {
	return xxx_messageInfo_SchemeCountRequest.Size(m)
}
func (m *SchemeCountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeCountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeCountRequest proto.InternalMessageInfo

func (m *SchemeCountRequest) GetFilter() string {
	if m != nil {
		return m.Filter
	}
	return ""
}

func (m *SchemeCountRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type SchemeCountResponse struct {
	Count                int64    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemeCountResponse) Reset()         { *m = SchemeCountResponse{} }
func (m *SchemeCountResponse) String() string { return proto.CompactTextString(m) }
func (*SchemeCountResponse) ProtoMessage()    {}
func (*SchemeCountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{27}
}

func (m *SchemeCountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeCountResponse.Unmarshal(m, b)
}
func (m *SchemeCountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeCountResponse.Marshal(b, m, deterministic)
}
func (m *SchemeCountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeCountResponse.Merge(m, src)
}
func (m *SchemeCountResponse) XXX_Size() int {
	return xxx_messageInfo_SchemeCountResponse.Size(m)
}
func (m *SchemeCountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeCountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeCountResponse proto.InternalMessageInfo

func (m *SchemeCountResponse) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type SchemeUpdateRequest struct {
	Where                string         `protobuf:"bytes,1,opt,name=where,proto3" json:"where,omitempty"`
	Scheme               *Scheme        `protobuf:"bytes,2,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SchemeUpdateRequest) Reset()         { *m = SchemeUpdateRequest{} }
func (m *SchemeUpdateRequest) String() string { return proto.CompactTextString(m) }
func (*SchemeUpdateRequest) ProtoMessage()    {}
func (*SchemeUpdateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{28}
}

func (m *SchemeUpdateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeUpdateRequest.Unmarshal(m, b)
}
func (m *SchemeUpdateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeUpdateRequest.Marshal(b, m, deterministic)
}
func (m *SchemeUpdateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeUpdateRequest.Merge(m, src)
}
func (m *SchemeUpdateRequest) XXX_Size() int {
	return xxx_messageInfo_SchemeUpdateRequest.Size(m)
}
func (m *SchemeUpdateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeUpdateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeUpdateRequest proto.InternalMessageInfo

func (m *SchemeUpdateRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

func (m *SchemeUpdateRequest) GetScheme() *Scheme {
	if m != nil {
		return m.Scheme
	}
	return nil
}

func (m *SchemeUpdateRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type SchemeUpdateResponse struct {
	Updated              bool     `protobuf:"varint,1,opt,name=updated,proto3" json:"updated,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemeUpdateResponse) Reset()         { *m = SchemeUpdateResponse{} }
func (m *SchemeUpdateResponse) String() string { return proto.CompactTextString(m) }
func (*SchemeUpdateResponse) ProtoMessage()    {}
func (*SchemeUpdateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{29}
}

func (m *SchemeUpdateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeUpdateResponse.Unmarshal(m, b)
}
func (m *SchemeUpdateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeUpdateResponse.Marshal(b, m, deterministic)
}
func (m *SchemeUpdateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeUpdateResponse.Merge(m, src)
}
func (m *SchemeUpdateResponse) XXX_Size() int {
	return xxx_messageInfo_SchemeUpdateResponse.Size(m)
}
func (m *SchemeUpdateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeUpdateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeUpdateResponse proto.InternalMessageInfo

func (m *SchemeUpdateResponse) GetUpdated() bool {
	if m != nil {
		return m.Updated
	}
	return false
}

type SchemeDeleteByIdRequest struct {
	Id                   string         `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SchemeDeleteByIdRequest) Reset()         { *m = SchemeDeleteByIdRequest{} }
func (m *SchemeDeleteByIdRequest) String() string { return proto.CompactTextString(m) }
func (*SchemeDeleteByIdRequest) ProtoMessage()    {}
func (*SchemeDeleteByIdRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{30}
}

func (m *SchemeDeleteByIdRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeDeleteByIdRequest.Unmarshal(m, b)
}
func (m *SchemeDeleteByIdRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeDeleteByIdRequest.Marshal(b, m, deterministic)
}
func (m *SchemeDeleteByIdRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeDeleteByIdRequest.Merge(m, src)
}
func (m *SchemeDeleteByIdRequest) XXX_Size() int {
	return xxx_messageInfo_SchemeDeleteByIdRequest.Size(m)
}
func (m *SchemeDeleteByIdRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeDeleteByIdRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeDeleteByIdRequest proto.InternalMessageInfo

func (m *SchemeDeleteByIdRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SchemeDeleteByIdRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type SchemeDeleteByIdResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemeDeleteByIdResponse) Reset()         { *m = SchemeDeleteByIdResponse{} }
func (m *SchemeDeleteByIdResponse) String() string { return proto.CompactTextString(m) }
func (*SchemeDeleteByIdResponse) ProtoMessage()    {}
func (*SchemeDeleteByIdResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{31}
}

func (m *SchemeDeleteByIdResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeDeleteByIdResponse.Unmarshal(m, b)
}
func (m *SchemeDeleteByIdResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeDeleteByIdResponse.Marshal(b, m, deterministic)
}
func (m *SchemeDeleteByIdResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeDeleteByIdResponse.Merge(m, src)
}
func (m *SchemeDeleteByIdResponse) XXX_Size() int {
	return xxx_messageInfo_SchemeDeleteByIdResponse.Size(m)
}
func (m *SchemeDeleteByIdResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeDeleteByIdResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeDeleteByIdResponse proto.InternalMessageInfo

func (m *SchemeDeleteByIdResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

type SchemeDeleteWithWhereRequest struct {
	Where                string         `protobuf:"bytes,1,opt,name=where,proto3" json:"where,omitempty"`
	Header               *RequestHeader `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *SchemeDeleteWithWhereRequest) Reset()         { *m = SchemeDeleteWithWhereRequest{} }
func (m *SchemeDeleteWithWhereRequest) String() string { return proto.CompactTextString(m) }
func (*SchemeDeleteWithWhereRequest) ProtoMessage()    {}
func (*SchemeDeleteWithWhereRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{32}
}

func (m *SchemeDeleteWithWhereRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeDeleteWithWhereRequest.Unmarshal(m, b)
}
func (m *SchemeDeleteWithWhereRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeDeleteWithWhereRequest.Marshal(b, m, deterministic)
}
func (m *SchemeDeleteWithWhereRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeDeleteWithWhereRequest.Merge(m, src)
}
func (m *SchemeDeleteWithWhereRequest) XXX_Size() int {
	return xxx_messageInfo_SchemeDeleteWithWhereRequest.Size(m)
}
func (m *SchemeDeleteWithWhereRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeDeleteWithWhereRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeDeleteWithWhereRequest proto.InternalMessageInfo

func (m *SchemeDeleteWithWhereRequest) GetWhere() string {
	if m != nil {
		return m.Where
	}
	return ""
}

func (m *SchemeDeleteWithWhereRequest) GetHeader() *RequestHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

type SchemeDeleteWithWhereResponse struct {
	Deleted              bool     `protobuf:"varint,1,opt,name=deleted,proto3" json:"deleted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SchemeDeleteWithWhereResponse) Reset()         { *m = SchemeDeleteWithWhereResponse{} }
func (m *SchemeDeleteWithWhereResponse) String() string { return proto.CompactTextString(m) }
func (*SchemeDeleteWithWhereResponse) ProtoMessage()    {}
func (*SchemeDeleteWithWhereResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_694536902d7906af, []int{33}
}

func (m *SchemeDeleteWithWhereResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SchemeDeleteWithWhereResponse.Unmarshal(m, b)
}
func (m *SchemeDeleteWithWhereResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SchemeDeleteWithWhereResponse.Marshal(b, m, deterministic)
}
func (m *SchemeDeleteWithWhereResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SchemeDeleteWithWhereResponse.Merge(m, src)
}
func (m *SchemeDeleteWithWhereResponse) XXX_Size() int {
	return xxx_messageInfo_SchemeDeleteWithWhereResponse.Size(m)
}
func (m *SchemeDeleteWithWhereResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SchemeDeleteWithWhereResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SchemeDeleteWithWhereResponse proto.InternalMessageInfo

func (m *SchemeDeleteWithWhereResponse) GetDeleted() bool {
	if m != nil {
		return m.Deleted
	}
	return false
}

func init() {
	proto.RegisterType((*Course)(nil), "pbx.Course")
	proto.RegisterType((*CourseFindRequest)(nil), "pbx.CourseFindRequest")
	proto.RegisterType((*CourseFindResponse)(nil), "pbx.CourseFindResponse")
	proto.RegisterType((*CourseFindOneRequest)(nil), "pbx.CourseFindOneRequest")
	proto.RegisterType((*CourseFindOneResponse)(nil), "pbx.CourseFindOneResponse")
	proto.RegisterType((*CourseCreateRequest)(nil), "pbx.CourseCreateRequest")
	proto.RegisterType((*CourseCreateResponse)(nil), "pbx.CourseCreateResponse")
	proto.RegisterType((*CourseFindByIdRequest)(nil), "pbx.CourseFindByIdRequest")
	proto.RegisterType((*CourseFindByIdResponse)(nil), "pbx.CourseFindByIdResponse")
	proto.RegisterType((*CourseCountRequest)(nil), "pbx.CourseCountRequest")
	proto.RegisterType((*CourseCountResponse)(nil), "pbx.CourseCountResponse")
	proto.RegisterType((*CourseUpdateRequest)(nil), "pbx.CourseUpdateRequest")
	proto.RegisterType((*CourseUpdateResponse)(nil), "pbx.CourseUpdateResponse")
	proto.RegisterType((*CourseDeleteByIdRequest)(nil), "pbx.CourseDeleteByIdRequest")
	proto.RegisterType((*CourseDeleteByIdResponse)(nil), "pbx.CourseDeleteByIdResponse")
	proto.RegisterType((*CourseDeleteWithWhereRequest)(nil), "pbx.CourseDeleteWithWhereRequest")
	proto.RegisterType((*CourseDeleteWithWhereResponse)(nil), "pbx.CourseDeleteWithWhereResponse")
	proto.RegisterType((*Scheme)(nil), "pbx.Scheme")
	proto.RegisterType((*SchemeFindRequest)(nil), "pbx.SchemeFindRequest")
	proto.RegisterType((*SchemeFindResponse)(nil), "pbx.SchemeFindResponse")
	proto.RegisterType((*SchemeFindOneRequest)(nil), "pbx.SchemeFindOneRequest")
	proto.RegisterType((*SchemeFindOneResponse)(nil), "pbx.SchemeFindOneResponse")
	proto.RegisterType((*SchemeCreateRequest)(nil), "pbx.SchemeCreateRequest")
	proto.RegisterType((*SchemeCreateResponse)(nil), "pbx.SchemeCreateResponse")
	proto.RegisterType((*SchemeFindByIdRequest)(nil), "pbx.SchemeFindByIdRequest")
	proto.RegisterType((*SchemeFindByIdResponse)(nil), "pbx.SchemeFindByIdResponse")
	proto.RegisterType((*SchemeCountRequest)(nil), "pbx.SchemeCountRequest")
	proto.RegisterType((*SchemeCountResponse)(nil), "pbx.SchemeCountResponse")
	proto.RegisterType((*SchemeUpdateRequest)(nil), "pbx.SchemeUpdateRequest")
	proto.RegisterType((*SchemeUpdateResponse)(nil), "pbx.SchemeUpdateResponse")
	proto.RegisterType((*SchemeDeleteByIdRequest)(nil), "pbx.SchemeDeleteByIdRequest")
	proto.RegisterType((*SchemeDeleteByIdResponse)(nil), "pbx.SchemeDeleteByIdResponse")
	proto.RegisterType((*SchemeDeleteWithWhereRequest)(nil), "pbx.SchemeDeleteWithWhereRequest")
	proto.RegisterType((*SchemeDeleteWithWhereResponse)(nil), "pbx.SchemeDeleteWithWhereResponse")
}

func init() { proto.RegisterFile("pbx/srm.proto", fileDescriptor_694536902d7906af) }

var fileDescriptor_694536902d7906af = []byte{
	// 992 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x58, 0x5f, 0x6b, 0xe3, 0x46,
	0x10, 0x47, 0x76, 0xac, 0xc4, 0xe3, 0x73, 0x48, 0x37, 0x6e, 0x6e, 0xa3, 0xbb, 0x80, 0xaa, 0xe3,
	0xc0, 0xb4, 0x34, 0x2d, 0x69, 0x5f, 0x4a, 0x1b, 0x38, 0x92, 0x10, 0xea, 0xa7, 0x03, 0x85, 0x23,
	0xa6, 0x0f, 0xe7, 0x3a, 0xd2, 0x86, 0x88, 0x8b, 0x25, 0x55, 0x5a, 0xf7, 0x12, 0xe8, 0x67, 0xe9,
	0x67, 0xe8, 0xb7, 0xeb, 0x6b, 0xd1, 0xee, 0xc8, 0x5a, 0xfd, 0xb3, 0x2c, 0x48, 0xfa, 0xe6, 0x9d,
	0xd9, 0x99, 0xf9, 0x69, 0xe6, 0xb7, 0xbf, 0x5d, 0x0c, 0xc3, 0xf0, 0xe6, 0xe1, 0xbb, 0x38, 0x5a,
	0x1c, 0x87, 0x51, 0xc0, 0x03, 0xd2, 0x0d, 0x6f, 0x1e, 0x8c, 0xbd, 0xc4, 0xe6, 0x04, 0x8b, 0x45,
	0xe0, 0x4b, 0xb3, 0xf5, 0x6f, 0x07, 0xf4, 0xf3, 0x60, 0x19, 0xc5, 0x8c, 0xec, 0x42, 0xc7, 0x73,
	0xa9, 0x66, 0x6a, 0xe3, 0xbe, 0xdd, 0xf1, 0x5c, 0x42, 0x60, 0xcb, 0x09, 0x5c, 0x46, 0x3b, 0xc2,
	0x22, 0x7e, 0x93, 0x11, 0xf4, 0xb8, 0xc7, 0xef, 0x19, 0xed, 0x0a, 0xa3, 0x5c, 0x10, 0x13, 0x06,
	0x2e, 0x8b, 0x9d, 0xc8, 0x0b, 0xb9, 0x17, 0xf8, 0x74, 0x4b, 0xf8, 0x54, 0x13, 0xa1, 0xb0, 0xed,
	0x44, 0xcc, 0xf5, 0x78, 0x4c, 0x7b, 0xa6, 0x36, 0xee, 0xd8, 0xe9, 0x32, 0xc9, 0x18, 0x7c, 0xf6,
	0x59, 0x44, 0x75, 0x53, 0x1b, 0xf7, 0x6c, 0xb9, 0x48, 0x6a, 0xf3, 0xc7, 0x90, 0xd1, 0x6d, 0x59,
	0x3b, 0xf9, 0x4d, 0x8e, 0x00, 0xc2, 0x88, 0xcd, 0x1c, 0x81, 0x96, 0xee, 0x08, 0x4f, 0x3f, 0x8c,
	0x18, 0xc2, 0x7f, 0x05, 0xfd, 0xd8, 0xb9, 0x63, 0x0b, 0x36, 0xf3, 0x5c, 0xda, 0x17, 0xde, 0x1d,
	0x69, 0x98, 0xb8, 0xe4, 0x00, 0xf4, 0x98, 0xcf, 0xf9, 0x32, 0xa6, 0x60, 0x6a, 0xe3, 0x1d, 0x1b,
	0x57, 0xe4, 0x2d, 0xec, 0x7a, 0x7e, 0xcc, 0x3d, 0xbe, 0x4c, 0x60, 0x26, 0x91, 0x03, 0x11, 0x39,
	0x54, 0xac, 0x13, 0x97, 0x7c, 0x0b, 0xfb, 0x67, 0xd3, 0xe9, 0x6c, 0xb6, 0x0c, 0xdd, 0x39, 0x67,
	0xee, 0xec, 0xd6, 0x63, 0xf7, 0x6e, 0x4c, 0x5f, 0x98, 0xdd, 0x71, 0xdf, 0xde, 0x3b, 0x9b, 0x4e,
	0x3f, 0x48, 0xc7, 0xa5, 0xb0, 0x93, 0x37, 0xa0, 0xcb, 0xca, 0x74, 0x68, 0x6a, 0xe3, 0xc1, 0xc9,
	0xe0, 0x38, 0xbc, 0x79, 0x38, 0xbe, 0x12, 0x26, 0x1b, 0x5d, 0xd6, 0x35, 0x7c, 0x21, 0x91, 0x5f,
	0x7a, 0xbe, 0x6b, 0xb3, 0x3f, 0x96, 0x2c, 0xe6, 0x09, 0xce, 0x5b, 0xef, 0x9e, 0xb3, 0x08, 0xe7,
	0x80, 0x2b, 0xf2, 0x35, 0xe8, 0x77, 0x6c, 0xee, 0xb2, 0x48, 0x4c, 0x63, 0x70, 0x42, 0x44, 0x46,
	0x8c, 0xfa, 0x55, 0x78, 0x6c, 0xdc, 0x61, 0xfd, 0x0c, 0x44, 0x4d, 0x1c, 0x87, 0x81, 0x1f, 0x33,
	0xf2, 0x16, 0xb6, 0x65, 0xe7, 0x62, 0xaa, 0x99, 0xdd, 0x15, 0x28, 0xb9, 0xd3, 0x4e, 0x7d, 0xd6,
	0x6f, 0x30, 0xca, 0x82, 0xdf, 0xfb, 0xec, 0x29, 0x81, 0xfd, 0x02, 0x5f, 0x16, 0x72, 0x23, 0xb6,
	0x37, 0xa0, 0xe3, 0x54, 0x35, 0xa5, 0x5f, 0x08, 0x0d, 0x5d, 0xd6, 0x2d, 0xec, 0x4b, 0xcb, 0x79,
	0xc4, 0xe6, 0x7c, 0x05, 0x6c, 0x93, 0xd8, 0x96, 0xed, 0x1b, 0xe5, 0xeb, 0xb4, 0x01, 0xf9, 0x49,
	0xfd, 0xc4, 0xb3, 0xc7, 0xc9, 0x6a, 0xb0, 0xc5, 0xc3, 0x95, 0xf5, 0xb3, 0x53, 0xd3, 0xcf, 0x6e,
	0x23, 0xd2, 0x53, 0x38, 0x28, 0x16, 0x6b, 0x83, 0x75, 0x9a, 0xf2, 0xe4, 0x3c, 0x58, 0xfa, 0xfc,
	0x29, 0x07, 0xfd, 0xcd, 0x6a, 0x54, 0x32, 0x33, 0xa2, 0x1a, 0x41, 0xcf, 0x49, 0x0c, 0x22, 0x73,
	0xd7, 0x96, 0x0b, 0xeb, 0xaf, 0x74, 0xb3, 0x3c, 0x43, 0x29, 0x8e, 0x11, 0xf4, 0x3e, 0xdf, 0xb1,
	0x88, 0x21, 0x0c, 0xb9, 0x50, 0x3e, 0xac, 0xb3, 0xc9, 0xb4, 0x9b, 0x7b, 0xf8, 0x7d, 0x3a, 0xed,
	0xb4, 0x3a, 0x62, 0xa5, 0xb0, 0x8d, 0x87, 0x5d, 0x00, 0xd8, 0xb1, 0xd3, 0xa5, 0xf5, 0x01, 0x5e,
	0xca, 0x88, 0x0b, 0x76, 0xcf, 0x38, 0x5b, 0x37, 0xe4, 0x36, 0x40, 0x7e, 0x04, 0x5a, 0x4e, 0x9b,
	0x81, 0x71, 0x85, 0x75, 0x05, 0x06, 0x97, 0xd6, 0xef, 0xf0, 0x5a, 0x8d, 0xba, 0xf6, 0xf8, 0xdd,
	0x75, 0xd2, 0xa8, 0xf5, 0x5d, 0x6c, 0x33, 0xcb, 0x9f, 0xe0, 0xa8, 0xa6, 0x42, 0x23, 0xb8, 0xbf,
	0x35, 0xd0, 0xa5, 0xe8, 0x55, 0xd1, 0x1f, 0x15, 0x12, 0xe9, 0x2f, 0x57, 0x8a, 0x4e, 0x77, 0x1b,
	0x74, 0x7a, 0xab, 0x85, 0x4e, 0xf7, 0xaa, 0x75, 0x3a, 0x91, 0x60, 0x89, 0xef, 0x19, 0x24, 0x58,
	0x4d, 0x9c, 0x49, 0xb0, 0xfc, 0xcc, 0xbc, 0x04, 0xe3, 0xbd, 0x90, 0xfa, 0x12, 0x09, 0xce, 0x82,
	0x9f, 0x5e, 0x82, 0x0b, 0xb9, 0x33, 0xc5, 0xc0, 0x81, 0x68, 0xf5, 0x57, 0xd6, 0x2d, 0xec, 0x4b,
	0x4b, 0x49, 0x82, 0x1b, 0x63, 0xdb, 0x4a, 0x70, 0xbe, 0x4e, 0x1b, 0x90, 0x9f, 0xd4, 0x4f, 0xfc,
	0x1f, 0x24, 0xb8, 0x58, 0xac, 0x0d, 0xd6, 0x69, 0xca, 0x93, 0xe7, 0x90, 0xe0, 0x5c, 0xe6, 0x26,
	0x09, 0x96, 0x9b, 0x37, 0x94, 0x60, 0xe5, 0xe8, 0x36, 0x4e, 0x7b, 0x23, 0x09, 0xce, 0x57, 0xdf,
	0x44, 0x82, 0x65, 0xc4, 0x93, 0x4b, 0x70, 0x39, 0xed, 0x26, 0x12, 0xac, 0x46, 0x3d, 0x8f, 0x04,
	0xd7, 0x54, 0x68, 0x02, 0x77, 0xf2, 0x4f, 0x1f, 0xf6, 0xce, 0xd8, 0xdc, 0x09, 0xfc, 0xab, 0x68,
	0x71, 0xc5, 0xa2, 0x3f, 0x3d, 0x87, 0x91, 0x73, 0x78, 0xa1, 0xbe, 0x70, 0x08, 0x55, 0x2e, 0xd1,
	0xdc, 0xc9, 0x36, 0x0e, 0x2b, 0x3c, 0x58, 0xf3, 0x14, 0x20, 0x7b, 0x7c, 0x90, 0x03, 0x65, 0xa3,
	0x22, 0xa6, 0xc6, 0xcb, 0x92, 0x1d, 0xc3, 0x2f, 0x61, 0x98, 0x7b, 0x0b, 0x92, 0xc3, 0xc2, 0xce,
	0x4c, 0xf8, 0x0c, 0xa3, 0xca, 0x85, 0x79, 0x26, 0xb0, 0x9b, 0x7b, 0x03, 0x5d, 0x90, 0xe2, 0x6e,
	0x85, 0x1d, 0xc6, 0xab, 0x4a, 0x1f, 0xa6, 0x7a, 0x07, 0x03, 0xe5, 0xd5, 0x42, 0x54, 0xe8, 0xea,
	0xf1, 0x34, 0x68, 0xd9, 0x81, 0x19, 0x56, 0x8d, 0x95, 0x4c, 0xce, 0x35, 0x36, 0x77, 0xb4, 0x72,
	0x8d, 0x2d, 0xd0, 0xfe, 0x3d, 0xec, 0x15, 0x1e, 0x02, 0x17, 0xe4, 0xb5, 0xb2, 0xbd, 0xc4, 0x79,
	0xe3, 0xa8, 0xc6, 0x8b, 0x09, 0x3f, 0xa6, 0x6f, 0xd2, 0x02, 0x7d, 0xc8, 0x57, 0xa5, 0xb8, 0x22,
	0x79, 0x0d, 0x6b, 0xdd, 0x96, 0xec, 0xab, 0x55, 0xb5, 0xc6, 0xaf, 0xae, 0xb8, 0x28, 0xf0, 0xab,
	0x2b, 0xa5, 0xfd, 0x14, 0x20, 0x13, 0x52, 0xa4, 0x53, 0xe9, 0x6e, 0x46, 0x3a, 0x55, 0x5c, 0xad,
	0x97, 0x30, 0xcc, 0xdd, 0x6b, 0xe4, 0xb0, 0xb0, 0xb3, 0x44, 0xa7, 0xea, 0x6b, 0x70, 0x02, 0xbb,
	0x39, 0x3d, 0x4f, 0xe9, 0x54, 0x79, 0xa3, 0x20, 0x9d, 0x6a, 0x2e, 0x80, 0x77, 0x30, 0x50, 0x14,
	0x98, 0xa8, 0xd0, 0x2b, 0xe8, 0x54, 0x25, 0xd6, 0xab, 0xc6, 0xe6, 0xe8, 0x54, 0xa1, 0xd4, 0xb9,
	0xc6, 0x96, 0xe9, 0x54, 0x10, 0xb5, 0x94, 0x4e, 0x35, 0x12, 0x8a, 0x74, 0xaa, 0x55, 0xc2, 0x8f,
	0xe9, 0xfd, 0x5a, 0x4d, 0xa7, 0x75, 0x5a, 0x88, 0x74, 0x5a, 0x2b, 0x66, 0x37, 0xba, 0xf8, 0x63,
	0xe2, 0x87, 0xff, 0x02, 0x00, 0x00, 0xff, 0xff, 0x1a, 0xeb, 0xf3, 0x96, 0xc0, 0x10, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// BeaconSrmServiceClient is the client API for BeaconSrmService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type BeaconSrmServiceClient interface {
	// Course
	CourseCreate(ctx context.Context, in *CourseCreateRequest, opts ...grpc.CallOption) (*CourseCreateResponse, error)
	CourseFind(ctx context.Context, in *CourseFindRequest, opts ...grpc.CallOption) (*CourseFindResponse, error)
	CourseFindOne(ctx context.Context, in *CourseFindOneRequest, opts ...grpc.CallOption) (*CourseFindOneResponse, error)
	CourseFindByID(ctx context.Context, in *CourseFindByIdRequest, opts ...grpc.CallOption) (*CourseFindByIdResponse, error)
	CourseCount(ctx context.Context, in *CourseCountRequest, opts ...grpc.CallOption) (*CourseCountResponse, error)
	CourseUpdate(ctx context.Context, in *CourseUpdateRequest, opts ...grpc.CallOption) (*CourseUpdateResponse, error)
	CourseDeleteByID(ctx context.Context, in *CourseDeleteByIdRequest, opts ...grpc.CallOption) (*CourseDeleteByIdResponse, error)
	CourseDeleteWithWhere(ctx context.Context, in *CourseDeleteWithWhereRequest, opts ...grpc.CallOption) (*CourseDeleteWithWhereResponse, error)
	// Scheme
	SchemeCreate(ctx context.Context, in *SchemeCreateRequest, opts ...grpc.CallOption) (*SchemeCreateResponse, error)
	SchemeFind(ctx context.Context, in *SchemeFindRequest, opts ...grpc.CallOption) (*SchemeFindResponse, error)
	SchemeFindOne(ctx context.Context, in *SchemeFindOneRequest, opts ...grpc.CallOption) (*SchemeFindOneResponse, error)
	SchemeFindByID(ctx context.Context, in *SchemeFindByIdRequest, opts ...grpc.CallOption) (*SchemeFindByIdResponse, error)
	SchemeCount(ctx context.Context, in *SchemeCountRequest, opts ...grpc.CallOption) (*SchemeCountResponse, error)
	SchemeUpdate(ctx context.Context, in *SchemeUpdateRequest, opts ...grpc.CallOption) (*SchemeUpdateResponse, error)
	SchemeDeleteByID(ctx context.Context, in *SchemeDeleteByIdRequest, opts ...grpc.CallOption) (*SchemeDeleteByIdResponse, error)
	SchemeDeleteWithWhere(ctx context.Context, in *SchemeDeleteWithWhereRequest, opts ...grpc.CallOption) (*SchemeDeleteWithWhereResponse, error)
}

type beaconSrmServiceClient struct {
	cc *grpc.ClientConn
}

func NewBeaconSrmServiceClient(cc *grpc.ClientConn) BeaconSrmServiceClient {
	return &beaconSrmServiceClient{cc}
}

func (c *beaconSrmServiceClient) CourseCreate(ctx context.Context, in *CourseCreateRequest, opts ...grpc.CallOption) (*CourseCreateResponse, error) {
	out := new(CourseCreateResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/CourseCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) CourseFind(ctx context.Context, in *CourseFindRequest, opts ...grpc.CallOption) (*CourseFindResponse, error) {
	out := new(CourseFindResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/CourseFind", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) CourseFindOne(ctx context.Context, in *CourseFindOneRequest, opts ...grpc.CallOption) (*CourseFindOneResponse, error) {
	out := new(CourseFindOneResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/CourseFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) CourseFindByID(ctx context.Context, in *CourseFindByIdRequest, opts ...grpc.CallOption) (*CourseFindByIdResponse, error) {
	out := new(CourseFindByIdResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/CourseFindByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) CourseCount(ctx context.Context, in *CourseCountRequest, opts ...grpc.CallOption) (*CourseCountResponse, error) {
	out := new(CourseCountResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/CourseCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) CourseUpdate(ctx context.Context, in *CourseUpdateRequest, opts ...grpc.CallOption) (*CourseUpdateResponse, error) {
	out := new(CourseUpdateResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/CourseUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) CourseDeleteByID(ctx context.Context, in *CourseDeleteByIdRequest, opts ...grpc.CallOption) (*CourseDeleteByIdResponse, error) {
	out := new(CourseDeleteByIdResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/CourseDeleteByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) CourseDeleteWithWhere(ctx context.Context, in *CourseDeleteWithWhereRequest, opts ...grpc.CallOption) (*CourseDeleteWithWhereResponse, error) {
	out := new(CourseDeleteWithWhereResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/CourseDeleteWithWhere", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) SchemeCreate(ctx context.Context, in *SchemeCreateRequest, opts ...grpc.CallOption) (*SchemeCreateResponse, error) {
	out := new(SchemeCreateResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/SchemeCreate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) SchemeFind(ctx context.Context, in *SchemeFindRequest, opts ...grpc.CallOption) (*SchemeFindResponse, error) {
	out := new(SchemeFindResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/SchemeFind", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) SchemeFindOne(ctx context.Context, in *SchemeFindOneRequest, opts ...grpc.CallOption) (*SchemeFindOneResponse, error) {
	out := new(SchemeFindOneResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/SchemeFindOne", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) SchemeFindByID(ctx context.Context, in *SchemeFindByIdRequest, opts ...grpc.CallOption) (*SchemeFindByIdResponse, error) {
	out := new(SchemeFindByIdResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/SchemeFindByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) SchemeCount(ctx context.Context, in *SchemeCountRequest, opts ...grpc.CallOption) (*SchemeCountResponse, error) {
	out := new(SchemeCountResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/SchemeCount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) SchemeUpdate(ctx context.Context, in *SchemeUpdateRequest, opts ...grpc.CallOption) (*SchemeUpdateResponse, error) {
	out := new(SchemeUpdateResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/SchemeUpdate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) SchemeDeleteByID(ctx context.Context, in *SchemeDeleteByIdRequest, opts ...grpc.CallOption) (*SchemeDeleteByIdResponse, error) {
	out := new(SchemeDeleteByIdResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/SchemeDeleteByID", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *beaconSrmServiceClient) SchemeDeleteWithWhere(ctx context.Context, in *SchemeDeleteWithWhereRequest, opts ...grpc.CallOption) (*SchemeDeleteWithWhereResponse, error) {
	out := new(SchemeDeleteWithWhereResponse)
	err := c.cc.Invoke(ctx, "/pbx.BeaconSrmService/SchemeDeleteWithWhere", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BeaconSrmServiceServer is the server API for BeaconSrmService service.
type BeaconSrmServiceServer interface {
	// Course
	CourseCreate(context.Context, *CourseCreateRequest) (*CourseCreateResponse, error)
	CourseFind(context.Context, *CourseFindRequest) (*CourseFindResponse, error)
	CourseFindOne(context.Context, *CourseFindOneRequest) (*CourseFindOneResponse, error)
	CourseFindByID(context.Context, *CourseFindByIdRequest) (*CourseFindByIdResponse, error)
	CourseCount(context.Context, *CourseCountRequest) (*CourseCountResponse, error)
	CourseUpdate(context.Context, *CourseUpdateRequest) (*CourseUpdateResponse, error)
	CourseDeleteByID(context.Context, *CourseDeleteByIdRequest) (*CourseDeleteByIdResponse, error)
	CourseDeleteWithWhere(context.Context, *CourseDeleteWithWhereRequest) (*CourseDeleteWithWhereResponse, error)
	// Scheme
	SchemeCreate(context.Context, *SchemeCreateRequest) (*SchemeCreateResponse, error)
	SchemeFind(context.Context, *SchemeFindRequest) (*SchemeFindResponse, error)
	SchemeFindOne(context.Context, *SchemeFindOneRequest) (*SchemeFindOneResponse, error)
	SchemeFindByID(context.Context, *SchemeFindByIdRequest) (*SchemeFindByIdResponse, error)
	SchemeCount(context.Context, *SchemeCountRequest) (*SchemeCountResponse, error)
	SchemeUpdate(context.Context, *SchemeUpdateRequest) (*SchemeUpdateResponse, error)
	SchemeDeleteByID(context.Context, *SchemeDeleteByIdRequest) (*SchemeDeleteByIdResponse, error)
	SchemeDeleteWithWhere(context.Context, *SchemeDeleteWithWhereRequest) (*SchemeDeleteWithWhereResponse, error)
}

func RegisterBeaconSrmServiceServer(s *grpc.Server, srv BeaconSrmServiceServer) {
	s.RegisterService(&_BeaconSrmService_serviceDesc, srv)
}

func _BeaconSrmService_CourseCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).CourseCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/CourseCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).CourseCreate(ctx, req.(*CourseCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_CourseFind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).CourseFind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/CourseFind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).CourseFind(ctx, req.(*CourseFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_CourseFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseFindOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).CourseFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/CourseFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).CourseFindOne(ctx, req.(*CourseFindOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_CourseFindByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseFindByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).CourseFindByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/CourseFindByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).CourseFindByID(ctx, req.(*CourseFindByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_CourseCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).CourseCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/CourseCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).CourseCount(ctx, req.(*CourseCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_CourseUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).CourseUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/CourseUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).CourseUpdate(ctx, req.(*CourseUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_CourseDeleteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseDeleteByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).CourseDeleteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/CourseDeleteByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).CourseDeleteByID(ctx, req.(*CourseDeleteByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_CourseDeleteWithWhere_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CourseDeleteWithWhereRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).CourseDeleteWithWhere(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/CourseDeleteWithWhere",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).CourseDeleteWithWhere(ctx, req.(*CourseDeleteWithWhereRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_SchemeCreate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemeCreateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).SchemeCreate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/SchemeCreate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).SchemeCreate(ctx, req.(*SchemeCreateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_SchemeFind_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemeFindRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).SchemeFind(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/SchemeFind",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).SchemeFind(ctx, req.(*SchemeFindRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_SchemeFindOne_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemeFindOneRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).SchemeFindOne(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/SchemeFindOne",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).SchemeFindOne(ctx, req.(*SchemeFindOneRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_SchemeFindByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemeFindByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).SchemeFindByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/SchemeFindByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).SchemeFindByID(ctx, req.(*SchemeFindByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_SchemeCount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemeCountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).SchemeCount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/SchemeCount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).SchemeCount(ctx, req.(*SchemeCountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_SchemeUpdate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemeUpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).SchemeUpdate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/SchemeUpdate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).SchemeUpdate(ctx, req.(*SchemeUpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_SchemeDeleteByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemeDeleteByIdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).SchemeDeleteByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/SchemeDeleteByID",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).SchemeDeleteByID(ctx, req.(*SchemeDeleteByIdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BeaconSrmService_SchemeDeleteWithWhere_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SchemeDeleteWithWhereRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BeaconSrmServiceServer).SchemeDeleteWithWhere(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/pbx.BeaconSrmService/SchemeDeleteWithWhere",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BeaconSrmServiceServer).SchemeDeleteWithWhere(ctx, req.(*SchemeDeleteWithWhereRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _BeaconSrmService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "pbx.BeaconSrmService",
	HandlerType: (*BeaconSrmServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CourseCreate",
			Handler:    _BeaconSrmService_CourseCreate_Handler,
		},
		{
			MethodName: "CourseFind",
			Handler:    _BeaconSrmService_CourseFind_Handler,
		},
		{
			MethodName: "CourseFindOne",
			Handler:    _BeaconSrmService_CourseFindOne_Handler,
		},
		{
			MethodName: "CourseFindByID",
			Handler:    _BeaconSrmService_CourseFindByID_Handler,
		},
		{
			MethodName: "CourseCount",
			Handler:    _BeaconSrmService_CourseCount_Handler,
		},
		{
			MethodName: "CourseUpdate",
			Handler:    _BeaconSrmService_CourseUpdate_Handler,
		},
		{
			MethodName: "CourseDeleteByID",
			Handler:    _BeaconSrmService_CourseDeleteByID_Handler,
		},
		{
			MethodName: "CourseDeleteWithWhere",
			Handler:    _BeaconSrmService_CourseDeleteWithWhere_Handler,
		},
		{
			MethodName: "SchemeCreate",
			Handler:    _BeaconSrmService_SchemeCreate_Handler,
		},
		{
			MethodName: "SchemeFind",
			Handler:    _BeaconSrmService_SchemeFind_Handler,
		},
		{
			MethodName: "SchemeFindOne",
			Handler:    _BeaconSrmService_SchemeFindOne_Handler,
		},
		{
			MethodName: "SchemeFindByID",
			Handler:    _BeaconSrmService_SchemeFindByID_Handler,
		},
		{
			MethodName: "SchemeCount",
			Handler:    _BeaconSrmService_SchemeCount_Handler,
		},
		{
			MethodName: "SchemeUpdate",
			Handler:    _BeaconSrmService_SchemeUpdate_Handler,
		},
		{
			MethodName: "SchemeDeleteByID",
			Handler:    _BeaconSrmService_SchemeDeleteByID_Handler,
		},
		{
			MethodName: "SchemeDeleteWithWhere",
			Handler:    _BeaconSrmService_SchemeDeleteWithWhere_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pbx/srm.proto",
}
